var acantontransdata=Array(
"為什麼|點解",
"什麼|乜嘢",
"這裡|呢度",
"這些|呢啲",
"難到|唔通",
"那裡|嗰度",
"那些|嗰啲",
"怎樣|點樣",
"看見|睇見",
"什麼|乜嘢",
"剛纔|頭先",
"不必|唔使",
"重要|緊要",
"緊要問題|重要問題%zhong4 yao4 wen4 ti2%/an important issue/",
"緊要性|重要性%zhong4 yao4 xing4%/importance/",
"緊要他人|重要他人%significant other",
"緊要數學著作列表|重要數學著作列表%List of important publications in mathematics",
"當然|梗係",
"梗係群|當然群%trivial group",
"梗係表示|當然表示%trivial representation",
"還有|重有",
"現在|而家",
"而家式|現在式%present tense",
"或者|抑或",
"只是|靜係",
"喜歡|中意",
"中意吵架|喜歡吵架%xi3 huan1 chao3 jia4%/quarrelsome/",
"不必|唔使",
"唔使要|不必要%bu2 bi4 yao4%/needless/unnecessary/",
"一起|一齊",
"故意|特登",
"還有|重有",
"就是|就係",
"東西|嘢",
"料理嘢軍|料理東西軍%Dotch Cooking Show",
"新加坡地鐵嘢線|新加坡地鐵東西線%East West MRT Line",
"東京地下鐵嘢線|東京地下鐵東西線%Tokyo Metro Tōzai Line",
"嘢伯利亞海|東西伯利亞海%East Siberian Sea",
"嘢線|東西線%Tōzai Line",
"嘢經濟走廊|東西經濟走廊%East-West Economic Corridor",
"沒有|冇",
"冇什麼|沒有什麼%mei2 you3 shen2 me5%/there's nothing (... about it)/",
"波蘭冇滅亡|波蘭沒有滅亡%Dąbrowski's Mazurka",
"冇共產黨就冇新中國|沒有共產黨就沒有新中國%Without the Communist Party, There Would Be No New China",
"這樣|噉",
"這麼|咁",
"誰|邊個",
"邊個人|誰人%The Who",
"和|同埋",
"多米尼加共同埋國|多米尼加共和國%duo1 mi3 ni2 jia1 gong4 he2 guo2%/Dominican Republic/",
"共同埋黨|共和黨%gong4 he2 dang3%/Republican Party/",
"共同埋黨人|共和黨人%gong4 he2 dang3 ren2%/a Republican party member/",
"共同埋國|共和國%gong4 he2 guo2%/republic/",
"共同埋政體|共和政體%gong1 he2 zheng4 ti3%/republican/",
"同埋藹|和藹%he2 ai3%/kindly/nice/amiable/",
"同埋風|和風%he2 feng1%/breeze/",
"同埋好|和好%he2 hao3%/to become reconciled/",
"同埋解|和解%he2 jie3%/conciliatory/become reconciled/",
"同埋平|和平%he2 ping2%/peace/",
"同埋平會談|和平會談%he2 ping2 hui4 tan2%/peace talks/peace discussions/",
"同埋平條約|和平條約%he2 ping2 tiao2 yue1%/peace treaty/",
"同埋善|和善%he2 shan4%/good-natured/",
"同埋尚|和尚%he2 shang5%/Buddhist monk/",
"同埋諧|和諧%he2 xie2%/harmonious/",
"同埋約|和約%he2 yue1%/peace treaty/",
"呼同埋浩特|呼和浩特%hu1 he2 hao4 te4%/Hohhot (capital of Inner Mongolia)/",
"教義同埋聖約|教義和聖約%jiao4 yi4 he2 sheng4 yue1%/Doctrine and Covenants/",
"捷克共同埋國|捷克共和國%jie2 ke4 gong4 he2 guo2%/Czech Republic/",
"諾貝爾同埋平獎|諾貝爾和平獎%nuo4 bei4 er3 he2 ping2 jiang3%/Nobel peace prize/",
"世界同埋平|世界和平%shi4 jie4 he2 ping2%/world piece/",
"頤同埋園|頤和園%yi2 he2 yuan2%/Summer Palace (in Beijing)/",
"永久同埋平|永久和平%yong3 jiu3 he2 ping2%/lasting peace/enduring peace/",
"中華人民共同埋國|中華人民共和國%zhong1 hua2 ren2 min2 gong4 he2 guo2%/The People's Republic of China/",
"一同埋會|一和會%Ichiwa-kai",
"一條同埋矢|一條和矢%Kazuya Ichijō",
"不飽同埋烴|不飽和烴%unsaturated hydrocarbon",
"中井同埋哉|中井和哉%Kazuya Nakai",
"中同埋反應|中和反應%neutralization",
"中同埋市|中和市%Jhonghe City",
"中國同埋平崛起|中國和平崛起%China's peaceful rise",
"中華人民共同埋國|中華人民共和國%People's Republic of China",
"中華人民共同埋國中央人民政府|中華人民共和國中央人民政府%Central People's Government",
"中華人民共同埋國中央軍事委員會主席|中華人民共和國中央軍事委員會主席%Supreme Military Command of the PRC",
"中華人民共同埋國主席|中華人民共和國主席%President of the People's Republic of China",
"中華人民共同埋國交通|中華人民共和國交通%Transport in the People's Republic of China",
"中華人民共同埋國人口|中華人民共和國人口%Demographics of the People's Republic of China",
"中華人民共同埋國人權|中華人民共和國人權%Human rights in the People's Republic of China",
"中華人民共同埋國全國運動會|中華人民共和國全國運動會%National Games of the People's Republic of China",
"中華人民共同埋國公安部|中華人民共和國公安部%Ministry of Public Security of the People's Republic of China",
"中華人民共同埋國史|中華人民共和國史%History of the People's Republic of China",
"中華人民共同埋國商務部|中華人民共和國商務部%Ministry of Commerce of the People's Republic of China",
"中華人民共同埋國國務院|中華人民共和國國務院%State Council of the People's Republic of China",
"中華人民共同埋國國務院總理|中華人民共和國國務院總理%Premier of the People's Republic of China",
"中華人民共同埋國國家安全部|中華人民共和國國家安全部%Ministry of State Security",
"中華人民共同埋國國家廣播電影電視總局|中華人民共和國國家廣播電影電視總局%State Administration of Radio, Film, and Television",
"中華人民共同埋國國家標準|中華人民共和國國家標準%Guobiao",
"中華人民共同埋國國家食品藥品監督管理局|中華人民共和國國家食品藥品監督管理局%State Food and Drug Administration",
"中華人民共同埋國國徽|中華人民共和國國徽%National Emblem of the People's Republic of China",
"中華人民共同埋國國旗|中華人民共和國國旗%Flag of the People's Republic of China",
"中華人民共同埋國國防部|中華人民共和國國防部%Ministry of National Defense of the People's Republic of China",
"中華人民共同埋國城市列表|中華人民共和國城市列表%List of cities in the People's Republic of China",
"中華人民共同埋國外交|中華人民共和國外交%Foreign relations of the People's Republic of China",
"中華人民共同埋國媒體|中華人民共和國媒體%Government control of the media in the People's Republic of China",
"中華人民共同埋國宗教|中華人民共和國宗教%Religion in China",
"中華人民共同埋國憲法|中華人民共和國憲法%Constitution of the People's Republic of China",
"中華人民共同埋國政府|中華人民共和國政府%Government of the People's Republic of China",
"中華人民共同埋國政治|中華人民共和國政治%Politics of the People's Republic of China",
"中華人民共同埋國政黨|中華人民共和國政黨%List of political parties in the People's Republic of China",
"中華人民共同埋國教育部|中華人民共和國教育部%Ministry of Education of the People's Republic of China",
"中華人民共同埋國最高人民檢察院|中華人民共和國最高人民檢察院%Supreme People's Procuratorate",
"中華人民共同埋國最高人民法院|中華人民共和國最高人民法院%Supreme People's Court of the People's Republic of China",
"中華人民共同埋國民法通則|中華人民共和國民法通則%General Principles of the Civil Law of the People's Republic of China",
"中華人民共同埋國法律|中華人民共和國法律%Law of the People's Republic of China",
"中華人民共同埋國的宣傳活動|中華人民共和國的宣傳活動%Propaganda in the People's Republic of China",
"中華人民共同埋國第十屆全運會|中華人民共和國第十屆全運會%10th National Games of the People's Republic of China",
"中華人民共同埋國經濟|中華人民共和國經濟%Economy of the People's Republic of China",
"中華人民共同埋國與世界各國建交簡表|中華人民共和國與世界各國建交簡表%Dates of establishment of diplomatic relations with the People's Republic of China",
"中華人民共同埋國行政區人口密度表|中華人民共和國行政區人口密度表%List of China administrative divisions by population density",
"中華人民共同埋國行政區人口表|中華人民共和國行政區人口表%List of China administrative divisions by population",
"中華人民共同埋國行政區劃|中華人民共和國行政區劃%Political divisions of China",
"中華人民共同埋國行政區國內生產總值表|中華人民共和國行政區國內生產總值表%List of China administrative divisions by GDP",
"中華人民共同埋國行政區面積表|中華人民共和國行政區面積表%List of China administrative divisions by area",
"中華人民共同埋國財政部|中華人民共和國財政部%Ministry of Finance of the People's Republic of China",
"中華人民共同埋國通信|中華人民共和國通信%Communications in the People's Republic of China",
"中華人民共同埋國道路交通安全法|中華人民共和國道路交通安全法%Road Traffic Safety Law of the People's Republic of China",
"中華人民共同埋國鐵路線路列表|中華人民共和國鐵路線路列表%List of railways in China",
"中華人民共同埋國鐵路運輸|中華人民共和國鐵路運輸%Rail transport in the People's Republic of China",
"中華民國與日本國間同埋平條約|中華民國與日本國間和平條約%Treaty of Taipei",
"中華蘇維埃共同埋國|中華蘇維埃共和國%Chinese Soviet Republic",
"中非共同埋國|中非共和國%Central African Republic",
"中非共同埋國國旗|中非共和國國旗%Flag of the Central African Republic",
"也門民主人民共同埋國|也門民主人民共和國%South Yemen",
"二宮同埋也|二宮和也%Kazunari Ninomiya",
"井上同埋彥|井上和彥%Kazuhiko Inoue",
"亞洲最早的共同埋國|亞洲最早的共和國%Earliest republics in Asia",
"亞琛同埋約|亞琛和約%Treaty of Aix-la-Chapelle",
"亞眠同埋約|亞眠和約%Treaty of Amiens",
"亞美尼亞蘇維埃社會主義共同埋國|亞美尼亞蘇維埃社會主義共和國%Armenian SSR",
"人民共同埋國|人民共和國%People's Republic",
"人道及同埋平組織列表|人道及和平組織列表%List of humanitarian and peace organizations",
"仁同埋寺|仁和寺%Ninna-ji",
"伊拉克共同埋國衛隊|伊拉克共和國衛隊%Iraqi Republican Guard",
"伊散德爾瓦納同埋羅克渡口戰役|伊散德爾瓦納和羅克渡口戰役%Battle of Isandlwana",
"伊斯蘭共同埋報|伊斯蘭共和報%Islamic Republic of Iran Broadcasting",
"伏爾加德意志人蘇維埃社會主義自治共同埋國|伏爾加德意志人蘇維埃社會主義自治共和國%Volga German Autonomous Soviet Socialist Republic",
"俄羅斯自治共同埋國|俄羅斯自治共和國%Republics of Russia",
"俄羅斯蘇維埃聯邦社會主義共同埋國|俄羅斯蘇維埃聯邦社會主義共和國%Russian SFSR",
"克羅地亞人民共同埋國|克羅地亞人民共和國%People's Republic of Croatia",
"克羅地亞社會主義共同埋國|克羅地亞社會主義共和國%Socialist Republic of Croatia",
"共同埋制|共和制%republic",
"共同埋國|共和國%List of republics",
"共同埋國戰歌|共和國戰歌%The Battle Hymn of the Republic",
"共同埋黨|共和黨%Republican Party",
"分部求同埋法|分部求和法%summation by parts",
"切比雪夫總同埋不等式|切比雪夫總和不等式%Chebyshev's sum inequality",
"剛果共同埋國|剛果共和國%Republic of the Congo",
"剛果共同埋國國旗|剛果共和國國旗%Flag of the Republic of the Congo",
"剛果民主共同埋國|剛果民主共和國%Democratic Republic of the Congo",
"剛果民主共同埋國國旗|剛果民主共和國國旗%Flag of the Democratic Republic of the Congo",
"剛果民主共同埋國省|剛果民主共和國省%Template:Provinces of the Democratic Republic of the Congo",
"剛鐸同埋亞爾諾重聯王國|剛鐸和亞爾諾重聯王國%Reunited Kingdom",
"加利福尼亞共同埋國|加利福尼亞共和國%California Republic",
"北奧塞梯-阿蘭共同埋國|北奧塞梯-阿蘭共和國%North Ossetia-Alania",
"北賽普勒斯土耳其共同埋國|北賽普勒斯土耳其共和國%Turkish Republic of Northern Cyprus",
"十同埋田市|十和田市%Towada, Aomori",
"十四點同埋平原則|十四點和平原則%Fourteen Points",
"協同埋信條|協和信條%Formula of Concord",
"協同埋大學|協和大學%Concordia University",
"協同埋廣場|協和廣場%Place de la Concorde",
"協同埋飛機|協和飛機%Concorde",
"南斯拉夫社會主義聯邦共同埋國|南斯拉夫社會主義聯邦共和國%Socialist Federal Republic of Yugoslavia",
"南非共同埋國|南非共和國%South Africa",
"卡內基國際同埋平基金會|卡內基國際和平基金會%Carnegie Endowment for International Peace",
"卡巴爾達-巴爾卡爾共同埋國|卡巴爾達-巴爾卡爾共和國%Kabardino-Balkaria",
"卡拉卡爾帕克斯坦自治共同埋國|卡拉卡爾帕克斯坦自治共和國%Karakalpakstan",
"卡拉恰伊-切爾克斯共同埋國|卡拉恰伊-切爾克斯共和國%Karachay-Cherkessia",
"卡爾梅克共同埋國|卡爾梅克共和國%Kalmykia",
"卡特邁國家公園同埋自然保護區|卡特邁國家公園和自然保護區%Katmai National Park and Preserve",
"卡瑪拉同埋阿瑪拉|卡瑪拉和阿瑪拉%Amala and Kamala",
"卡累利阿共同埋國|卡累利阿共和國%Republic of Karelia",
"卡累利阿-芬蘭蘇維埃社會主義共同埋國|卡累利阿-芬蘭蘇維埃社會主義共和國%Karelo-Finnish SSR",
"印古什共同埋國|印古什共和國%Ingushetia",
"台北捷運中同埋線|台北捷運中和線%Zhonghe Line",
"台灣共同埋國|台灣共和國%Republic of Taiwan",
"合同埋中心|合和中心%Hopewell Centre, Hong Kong",
"合同埋公路基建|合和公路基建%Hopewell Highway Infrastructure",
"合同埋實業|合和實業%Hopewell Holdings",
"吉爾吉斯共同埋國國歌|吉爾吉斯共和國國歌%National Anthem of the Kyrgyz Republic",
"吉爾吉斯蘇維埃社會主義共同埋國|吉爾吉斯蘇維埃社會主義共和國%Kyrgyz SSR",
"呼同埋浩特市|呼和浩特市%Hohhot",
"同埋合石|和合石%Wo Hop Shek",
"同埋好教|和好教%Hoa Hao",
"同埋子說|和子說%filioque clause",
"同埋宮親子內親王|和宮親子內親王%Kazu-no-Miya Chikako",
"同埋寒町|和寒町%Wassamu, Hokkaidō",
"同埋尚|和尚%bhikkhu",
"同埋平|和平%peace",
"同埋平主義|和平主義%pacifism",
"同埋平共處五項原則|和平共處五項原則%Five Principles of Peaceful Coexistence",
"同埋平區|和平區%Heping District, Tianjin",
"同埋平於世|和平於世%Pacem in Terris",
"同埋平條約|和平條約%peace treaty",
"同埋平號太空站|和平號太空站%mir",
"同埋平飯店|和平飯店%Peace Hotel",
"同埋平鳥科|和平鳥科%fairy-bluebird",
"同埋式廁所|和式廁所%Toilets in Japan",
"同埋弦|和弦%Chord",
"同埋月伸宏|和月伸宏%Nobuhiro Watsuki",
"同埋服|和服%kimono",
"同埋歌|和歌%Waka",
"同埋歌山縣|和歌山縣%Wakayama Prefecture",
"同埋氏璧|和氏璧%He Shi Bi",
"同埋泉國|和泉國%Izumi Province",
"同埋珅|和珅%Heshen",
"同埋田市|和田市%Hotan",
"同埋田毅|和田毅%Tsuyoshi Wada",
"同埋田茂穗|和田茂穗%Shigeho Wada",
"同埋田薰|和田薰%Kaoru Wada",
"同埋算|和算%Japanese mathematics",
"同埋紙|和紙%washi",
"同埋縣|和縣%He County",
"同埋美鎮|和美鎮%Hemei, Changhua",
"同埋聲|和聲%harmony",
"同埋製英語|和製英語%wasei-eigo",
"同埋親|和親%Heqin",
"同埋記黃埔|和記黃埔%Hutchison Whampoa",
"同埋諧社會|和諧社會%harmonious society",
"哈卡斯共同埋國|哈卡斯共和國%Khakassia",
"哈拉同埋林|哈拉和林%Karakorum",
"哈薩克蘇維埃社會主義共同埋國|哈薩克蘇維埃社會主義共和國%Kazakh SSR",
"哥倫比亞共同埋國|哥倫比亞共和國%Colombia",
"單元不飽同埋脂肪|單元不飽和脂肪%monounsaturated fat",
"國際同埋平日|國際和平日%International Day of Peace",
"圖瓦人民共同埋國|圖瓦人民共和國%Tuvinian People's Republic",
"圖瓦共同埋國|圖瓦共和國%Tuva",
"土庫曼蘇維埃社會主義共同埋國|土庫曼蘇維埃社會主義共和國%Turkmen SSR",
"塔吉克蘇維埃社會主義共同埋國|塔吉克蘇維埃社會主義共和國%Tajik SSR",
"塞族共同埋國|塞族共和國%Republika Srpska",
"塞爾維亞克拉伊納共同埋國|塞爾維亞克拉伊納共和國%Republic of Serbian Krajina",
"外高加索蘇維埃聯邦社會主義共同埋國|外高加索蘇維埃聯邦社會主義共和國%Transcaucasian SFSR",
"多元不飽同埋脂肪|多元不飽和脂肪%polyunsaturated fat",
"多明尼加共同埋國|多明尼加共和國%Dominican Republic",
"多米尼加共同埋國國旗|多米尼加共和國國旗%Flag of the Dominican Republic",
"多米尼加共同埋國經濟|多米尼加共和國經濟%Economy of the Dominican Republic",
"大同埋國|大和國%Yamato Province",
"大同埋市|大和市%Yamato, Kanagawa",
"大同埋族|大和族%Yamato people",
"大同埋時代|大和時代%Yamato period",
"大同埋級戰列艦|大和級戰列艦%Yamato class battleship",
"大同埋郡山市|大和郡山市%Yamato-Kōriyama, Nara",
"大同埋高田市|大和高田市%Yamatotakada, Nara",
"大教堂同埋市集|大教堂和市集%The Cathedral and the Bazaar",
"太同埋殿|太和殿%Hall of Supreme Harmony",
"太同埋站|太和站%Tai Wo Station",
"夫朗同埋斐譜線|夫朗和斐譜線%Fraunhofer lines",
"奇斯帕達納共同埋國|奇斯帕達納共和國%Cispadane Republic",
"奧地利第一共同埋國|奧地利第一共和國%First Austrian Republic",
"奧布同埋約|奧布和約%Treaty of Åbo",
"妹島同埋世|妹島和世%Kazuyo Sejima",
"威尼斯共同埋國|威尼斯共和國%Republic of Venice",
"威斯特法倫同埋約|威斯特法倫和約%Peace of Westphalia",
"宇宙戰艦大同埋號|宇宙戰艦大和號%Space Battleship Yamato",
"山崎同埋佳奈|山崎和佳奈%Wakana Yamazaki",
"岡比亞共同埋國|岡比亞共和國%The Gambia",
"岸同埋田市|岸和田市%Kishiwada, Osaka",
"峰倉同埋也|峰倉和也%Kazuya Minekura",
"川島同埋津實|川島和津實%Azumi Kawashima",
"巴什科爾託斯坦共同埋國|巴什科爾託斯坦共和國%Bashkortostan",
"巴黎同埋會|巴黎和會%Paris Peace Conference, 1919",
"布袋同埋尚|布袋和尚%Budai",
"布裡亞特共同埋國|布裡亞特共和國%Buryatia",
"帕特裡克·肯尼迪同埋羅斯·菲茨傑拉德·肯尼迪的後裔|帕特裡克·肯尼迪和羅斯·菲茨傑拉德·肯尼迪的後裔%List of descendants of Joseph P. and Rose Fitzgerald Kennedy",
"廣島同埋平紀念公園|廣島和平紀念公園%Hiroshima Peace Memorial",
"彿得角共同埋國|彿得角共和國%Cape Verde",
"彿蒙特共同埋國|彿蒙特共和國%Vermont Republic",
"得克薩斯共同埋國|得克薩斯共和國%Republic of Texas",
"德川同埋子|德川和子%Tokugawa Masako",
"德意志民主共同埋國|德意志民主共和國%East Germany",
"德涅斯特河沿岸共同埋國|德涅斯特河沿岸共和國%transnistria",
"怡同埋大廈|怡和大廈%Jardine House",
"怡同埋洋行|怡和洋行%Jardine Matheson Holdings",
"怡同埋街|怡和街%Yee Wo Street",
"意大利社會共同埋國|意大利社會共和國%Italian Social Republic",
"愛因斯坦求同埋約定|愛因斯坦求和約定%Einstein notation",
"愛沙尼亞蘇維埃社會主義共同埋國|愛沙尼亞蘇維埃社會主義共和國%Estonian SSR",
"愛爾蘭共同埋國|愛爾蘭共和國%Irish Republic",
"愛爾蘭共同埋國國旗|愛爾蘭共和國國旗%Flag of Ireland",
"愛爾蘭共同埋軍|愛爾蘭共和軍%Irish Republican Army",
"愛爾蘭共同埋黨|愛爾蘭共和黨%Fianna Fáil",
"慶同埋省|慶和省%Khanh Hoa Province",
"戰爭與同埋平|戰爭與和平%War and Peace",
"拉脫維亞蘇維埃社會主義共同埋國|拉脫維亞蘇維埃社會主義共和國%Latvian SSR",
"捷克共同埋國國徽|捷克共和國國徽%Coat of arms of the Czech Republic",
"捷克共同埋國總理|捷克共和國總理%List of Prime Ministers of the Czech Republic",
"捷克共同埋國總統|捷克共和國總統%List of Presidents of Czechoslovakia",
"捷克斯洛伐克社會主義共同埋國|捷克斯洛伐克社會主義共和國%Czechoslovak Socialist Republic",
"摩爾達維亞蘇維埃社會主義共同埋國|摩爾達維亞蘇維埃社會主義共和國%Moldavian SSR",
"撒拉威阿拉伯民主共同埋國|撒拉威阿拉伯民主共和國%Sahrawi Arab Democratic Republic",
"斯德哥爾摩國際同埋平研究所|斯德哥爾摩國際和平研究所%Stockholm International Peace Research Institute",
"新加坡共同埋國武裝部隊|新加坡共和國武裝部隊%Singapore Armed Forces",
"新加坡共同埋國海軍部隊|新加坡共和國海軍部隊%Republic of Singapore Navy",
"日俄同埋親通好條約|日俄和親通好條約%Treaty of Shimoda",
"明同埋產業株式會社|明和產業株式會社%Meiwa Corp.",
"星雲同埋星團新總表|星雲和星團新總表%New General Catalogue",
"昭同埋之日|昭和之日%Shōwa Day",
"昭同埋區|昭和區%Shōwa-ku, Nagoya",
"昭同埋天皇|昭和天皇%Hirohito",
"朝鮮民主主義人民共同埋國|朝鮮民主主義人民共和國%North Korea",
"朝鮮民主主義人民共同埋國國防委員會|朝鮮民主主義人民共和國國防委員會%Chairman of the National Defense Commission of North Korea",
"東大同埋市|東大和市%Higashiyamato, Tokyo",
"格魯吉亞蘇維埃社會主義共同埋國|格魯吉亞蘇維埃社會主義共和國%Georgian SSR",
"楚瓦什共同埋國|楚瓦什共和國%Chuvashia",
"樸次茅斯同埋約|樸次茅斯和約%Treaty of Portsmouth",
"比利牛斯同埋約|比利牛斯和約%Treaty of the Pyrenees",
"比尤特-銀弓市同埋縣|比尤特-銀弓市和縣%Silver Bow County, Montana",
"民主同埋平論|民主和平論%democratic peace theory",
"永同埋市|永和市%Yonghe City",
"法國人權同埋公民權宣言|法國人權和公民權宣言%Declaration of the Rights of Man and of the Citizen",
"法國共同埋曆|法國共和曆%French Republican Calendar",
"法蘭西第一共同埋國|法蘭西第一共和國%French First Republic",
"法蘭西第三共同埋國|法蘭西第三共和國%French Third Republic",
"法蘭西第二共同埋國|法蘭西第二共和國%French Second Republic",
"法蘭西第五共同埋國|法蘭西第五共和國%French Fifth Republic",
"法蘭西第四共同埋國|法蘭西第四共和國%French Fourth Republic",
"波斯尼亞同埋黑塞哥維那|波斯尼亞和黑塞哥維那%Bosnia and Herzegovina",
"波蘭人民共同埋國|波蘭人民共和國%People's Republic of Poland",
"波蘭第二共同埋國|波蘭第二共和國%Second Polish Republic",
"浦同埋紅鑽|浦和紅鑽%Urawa Red Diamonds",
"海螺共同埋國|海螺共和國%Conch Republic",
"淳同埋天皇|淳和天皇%Emperor Junna",
"清同埋天皇|清和天皇%Emperor Seiwa",
"溫得同埋克|溫得和克%Windhoek",
"漢同埋帝|漢和帝%Emperor He of Han",
"烏克蘭蘇維埃社會主義共同埋國|烏克蘭蘇維埃社會主義共和國%Ukrainian SSR",
"烏兹別克蘇維埃社會主義共同埋國|烏兹別克蘇維埃社會主義共和國%Uzbek SSR",
"烏得勒支同埋約|烏得勒支和約%Treaty of Utrecht",
"烏德穆爾特共同埋國|烏德穆爾特共和國%Udmurtia",
"熱那亞共同埋國|熱那亞共和國%Republic of Genoa",
"特拉華、拉克瓦納同埋西部鐵路公司|特拉華、拉克瓦納和西部鐵路公司%Delaware, Lackawanna and Western Railroad",
"特立尼達同埋多巴哥共同埋國|特立尼達和多巴哥共和國%Economy of Trinidad and Tobago",
"白俄羅斯蘇維埃社會主義共同埋國|白俄羅斯蘇維埃社會主義共和國%Byelorussian SSR",
"真因子同埋數列|真因子和數列%aliquot sequence",
"科米共同埋國|科米共和國%Komi Republic",
"立陶宛蘇維埃社會主義共同埋國|立陶宛蘇維埃社會主義共和國%Lithuanian SSR",
"第二亞琛同埋約|第二亞琛和約%Treaty of Aix-la-Chapelle",
"第五共同埋國運動|第五共和國運動%Fifth Republic Movement",
"納希切萬自治共同埋國|納希切萬自治共和國%Nakhchivan",
"紹興同埋議|紹興和議%Treaty of Shaoxing",
"綠色同埋平|綠色和平%Greenpeace",
"網頁親同埋力|網頁親和力%web accessibility",
"緩同埋政策|緩和政策%détente",
"緬甸聯邦國家同埋平與發展委員會|緬甸聯邦國家和平與發展委員會%State Peace and Development Council",
"總同埋生育率|總和生育率%total fertility rate",
"羅馬共同埋國|羅馬共和國%Roman Republic",
"羅馬尼亞社會主義共同埋國|羅馬尼亞社會主義共和國%Communist Romania",
"義同埋團|義和團%Righteous Harmony Society",
"義同埋團運動|義和團運動%Boxer Rebellion",
"耶同埋華|耶和華%Yahweh",
"耶同埋華見證人|耶和華見證人%Jehovah's Witnesses",
"耶同埋華見證人出版物列表|耶和華見證人出版物列表%List of Watchtower publications",
"耶同埋華見證人同埋各國政府|耶和華見證人和各國政府%Jehovah's Witnesses and governments",
"耶同埋華見證人同埋血|耶和華見證人和血%Jehovah's Witnesses and blood transfusions",
"耶同埋華見證人基督徒會眾|耶和華見證人基督徒會眾%Christian Congregation of Jehovah's Witnesses",
"耶同埋華見證人的合法機構|耶和華見證人的合法機構%Legal instruments of Jehovah's Witnesses",
"耶同埋華見證人的末世論|耶和華見證人的末世論%Eschatology of Jehovah's Witnesses",
"耶同埋華見證人的治理機構|耶和華見證人的治理機構%Governing Body of Jehovah's Witnesses",
"耶同埋華見證人的組織結構|耶和華見證人的組織結構%Organizational structure of Jehovah's Witnesses",
"耶同埋華見證人的被迫害史|耶和華見證人的被迫害史%Persecution of Jehovah's Witnesses",
"聖皮埃爾同埋密克隆群島|聖皮埃爾和密克隆群島%Saint Pierre and Miquelon",
"聯合國維持同埋平部隊|聯合國維持和平部隊%peacekeeping",
"聯合阿拉伯共同埋國|聯合阿拉伯共和國%United Arab Republic",
"自治共同埋國|自治共和國%Autonomous republic",
"舊金山同埋約|舊金山和約%Treaty of San Francisco",
"芬蘭民主共同埋國|芬蘭民主共和國%Finnish Democratic Republic",
"莫爾多瓦共同埋國|莫爾多瓦共和國%Mordovia",
"蒙古人民共同埋國|蒙古人民共和國%Mongolian People's Republic",
"薩哈共同埋國|薩哈共和國%Sakha Republic",
"蘇丹共同埋國|蘇丹共和國%Sudan",
"蘇聯加盟共同埋國|蘇聯加盟共和國%Republics of the Soviet Union",
"蘇聯自治共同埋國|蘇聯自治共和國%Autonomous republics of the Soviet Union",
"蘭芳共同埋國|蘭芳共和國%Lanfang Republic",
"蝦夷共同埋國|蝦夷共和國%Republic of Ezo",
"袁同埋平|袁和平%Yuen Woo-ping",
"裡加同埋約|裡加和約%Peace of Riga",
"裡夫共同埋國|裡夫共和國%Republic of the Rif",
"西波士尼亞共同埋國|西波士尼亞共和國%Western Bosnia",
"西班牙治下的同埋平|西班牙治下的和平%Pax Hispanica",
"親同埋色譜|親和色譜%affinity chromatography",
"調同埋平均數|調和平均數%harmonic mean",
"調同埋數|調和數%harmonic divisor number",
"調同埋級數|調和級數%Harmonic series",
"諾同埋諾德|諾和諾德%Novo Nordisk",
"諾貝爾同埋平獎|諾貝爾和平獎%Nobel Peace Prize",
"警覺的同埋平時期|警覺的和平時期%Watchful Peace",
"費馬平方同埋定理|費馬平方和定理%Proofs of Fermat's theorem on sums of two squares",
"超大同埋型戰艦|超大和型戰艦%Super Yamato class battleship",
"越南共同埋國|越南共和國%South Vietnam",
"車臣共同埋國|車臣共和國%Chechnya",
"達吉斯坦共同埋國|達吉斯坦共和國%Dagestan",
"遠山同埋葉|遠山和葉%Kazuha Toyama",
"遠東共同埋國|遠東共和國%Far Eastern Republic",
"邏輯同埋諧|邏輯和諧%Logical harmony",
"關於耶同埋華見證人的論戰|關於耶和華見證人的論戰%Controversies regarding Jehovah's Witnesses",
"阿塞拜疆蘇維埃社會主義共同埋國|阿塞拜疆蘇維埃社會主義共和國%Azerbaijan SSR",
"阿拉伯也門共同埋國|阿拉伯也門共和國%North Yemen",
"阿迪格共同埋國|阿迪格共和國%Adygea",
"阿部同埋重|阿部和重%Kazushige Abe",
"雍同埋宮|雍和宮%Yonghe Temple",
"零同埋博弈|零和博弈%zero-sum",
"韃靼斯坦共同埋國|韃靼斯坦共和國%Tatarstan",
"頤同埋園|頤和園%Summer Palace",
"飽同埋蒸氣壓|飽和蒸氣壓%saturation vapor pressure",
"馬其頓共同埋國|馬其頓共和國%Republic of Macedonia",
"馬其頓共同埋國總統|馬其頓共和國總統%President of the Republic of Macedonia",
"馬其頓社會主義共同埋國|馬其頓社會主義共和國%Socialist Republic of Macedonia",
"馬裡共同埋國|馬裡共和國%mali",
"馬裡埃爾共同埋國|馬裡埃爾共和國%Mari El",
"高橋同埋希|高橋和希%Kazuki Takahashi",
"魏瑪共同埋國|魏瑪共和國%Weimar Republic",
"黑海蘇維埃共同埋國|黑海蘇維埃共和國%Black Sea Soviet Republic",
"龜梨同埋也|龜梨和也%Kazuya Kamenashi",
"中同埋殿|中和殿%Hall of Central Harmony",
"中華人民共同埋國交通部|中華人民共和國交通部%Ministry of Communications of the People's Republic of China",
"中華人民共同埋國人權|中華人民共和國人權%Human rights in the People's Republic of China/Temporary",
"中華人民共同埋國人民法院組織法|中華人民共和國人民法院組織法%Organic Law of the People's Courts of the People's Republic of China",
"中華人民共同埋國史|中華人民共和國史%History of the People's Republic of China",
"中華人民共同埋國國家最高科學技術獎|中華人民共和國國家最高科學技術獎%State Preeminent Science and Technology Award",
"中華人民共同埋國國家民族事務委員會|中華人民共和國國家民族事務委員會%State Ethnic Affairs Commission",
"中華人民共同埋國國家發展同埋改革委員會|中華人民共和國國家發展和改革委員會%National Development and Reform Commission",
"中華人民共同埋國國家知識產權局|中華人民共和國國家知識產權局%State Intellectual Property Office",
"中華人民共同埋國國慶節|中華人民共和國國慶節%National Day of the People's Republic of China",
"中華人民共同埋國國籍法|中華人民共和國國籍法%Nationality Law of the People's Republic of China",
"中華人民共同埋國外交部|中華人民共和國外交部%Foreign Minister of the People's Republic of China",
"中華人民共同埋國外匯儲備|中華人民共和國外匯儲備%Foreign exchange reserve of PRC",
"中華人民共同埋國審計署|中華人民共和國審計署%National Audit Office of the People's Republic of China",
"中華人民共同埋國水利部|中華人民共和國水利部%Ministry of Water Resources",
"中華人民共同埋國海軍|中華人民共和國海軍%Naval Weaponry of the People's Liberation Army Navy",
"中華人民共同埋國物權法|中華人民共和國物權法%Property Law of the People's Republic of China",
"中華人民共同埋國監察部|中華人民共和國監察部%Ministry of Supervision of the People's Republic of China",
"中華人民共同埋國行政區人類發展指數表|中華人民共和國行政區人類發展指數表%List of administrative divisions of the People's Republic of China by Human Development Index",
"中華人民共同埋國衛生部|中華人民共和國衛生部%Ministry of Health",
"中華人民共同埋國護照|中華人民共和國護照%People's Republic of China passport",
"中華人民共同埋國軍力報告|中華人民共和國軍力報告%Military Power of the People's Republic of China",
"中華人民共同埋國醫療體制改革|中華人民共和國醫療體制改革%Healthcare system reform in the People's Republic of China",
"中華人民共同埋國鐵路客運|中華人民共和國鐵路客運%Passenger rail transport in China",
"中華人民共同埋國鐵道部|中華人民共和國鐵道部%Chinese Ministry of Railways",
"中華人民共同埋國駐外機構|中華人民共和國駐外機構%People's Republic of China diplomatic missions",
"中華共同埋國|中華共和國%Fujian People's Government",
"二二八同埋平紀念公園|二二八和平紀念公園%228 Memorial Park",
"保同埋殿|保和殿%Hall of Preserving Harmony",
"八同埋會館|八和會館%Chinese Artist Association of Hong Kong",
"六同埋塔|六和塔%Liuhe Pagoda",
"共同埋立憲制|共和立憲制%constitutional republic",
"呼同埋浩特白塔國際機場|呼和浩特白塔國際機場%Hohhot Baita International Airport",
"呼同埋浩特足球俱樂部|呼和浩特足球俱樂部%Hohhot Black Horse",
"同埋久井映見|和久井映見%Emi Wakui",
"同埋富道|和富道%Wharf Road",
"同埋布克賽爾蒙古自治縣|和布克賽爾蒙古自治縣%Hoboksar Mongol Autonomous County",
"同埋平|和平%Peace",
"同埋平共處五項原則|和平共處五項原則%Panchsheel",
"同埋平基金會|和平基金會%Fund for Peace",
"同埋平省|和平省%Hoa Binh Province",
"同埋平紀念碑|和平紀念碑%The Cenotaph",
"同埋平鄉|和平鄉%Heping, Taichung",
"同埋歌山大學|和歌山大學%Wakayama University",
"同埋歌山市|和歌山市%Wakayama, Wakayama",
"同埋田一浩|和田一浩%Kazuhiro Wada",
"同埋田市|和田市%Charklik",
"同埋田慎二|和田慎二%Shinji Wada",
"同埋田縣|和田縣%Hotan County",
"同埋碩縣|和碩縣%Hoxud County",
"同埋記環球電訊|和記環球電訊%Hutchison Global Communications",
"同埋銅|和銅%Wadō",
"同埋靜縣|和靜縣%Hejing County",
"塞爾維亞社會主義共同埋國|塞爾維亞社會主義共和國%Socialist Republic of Serbia",
"大同埋悠河|大和悠河%Yūga Yamato",
"大哥倫比亞共同埋國|大哥倫比亞共和國%Gran Colombia",
"孝同埋睿皇後|孝和睿皇後%Empress XiaoHe",
"平同埋縣|平和縣%Pinghe County",
"廣島同埋平紀念公園|廣島和平紀念公園%Hiroshima Peace Memorial Park",
"應同埋會館|應和會館%Ying Fo Fui Kun",
"斯洛文尼亞社會主義共同埋國|斯洛文尼亞社會主義共和國%Socialist Republic of Slovenia",
"新同埋縣|新和縣%Toksu County",
"曾我部同埋恭|曾我部和恭%Kazuyuki Sogabe",
"有吉佐同埋子|有吉佐和子%Sawako Ariyoshi",
"民主同埋平論|民主和平論%List of possible exceptions to the democratic peace theory",
"沙茲爾共同埋國|沙茲爾共和國%Republic of Saugeais",
"波多野同埋俊|波多野和俊%Kazutoshi Hatano",
"波斯尼亞同埋黑塞哥維那社會主義共同埋國|波斯尼亞和黑塞哥維那社會主義共和國%Socialist Republic of Bosnia and Herzegovina",
"清原同埋博|清原和博%Kazuhiro Kiyohara",
"籐田同埋日郎|籐田和日郎%Kazuhiro Fujita",
"耶同埋華見證人的信條|耶和華見證人的信條%Beliefs and practices of Jehovah's Witnesses",
"聯同埋墟|聯和墟%Luen Wo Hui",
"西班牙第二共同埋國|西班牙第二共和國%Second Spanish Republic",
"豐同埋64式|豐和64式%Howa Type 64",
"養同埋醫院|養和醫院%Hong Kong Sanatorium and Hospital",
"香蕉共同埋國|香蕉共和國%banana republic",
"黑山社會主義共同埋國|黑山社會主義共和國%Socialist Republic of Montenegro",
"黑社會以同埋為貴|黑社會以和為貴%Election 2",
"齊籐同埋巳|齊籐和巳%Kazumi Saitoh",
"這|呢",
"在呢期間|在這期間%zai4 zhe4 qi1 jian1%/during time/in this time/",
"呢類|這類%zhe4 lei4%/this kind (of)/",
"呢裡|這裡%zhe4 li3%/here/",
"呢麼|這麼%zhe4 me5%/so (much)/like this/",
"呢兒|這兒%zher4%/here/",
"呢天|這天%zhe4 tian1%/today/this day/",
"呢位|這位%zhe4 wei4%/this (person)/",
"呢項|這項%zhe4 xiang4%/this (thing)/",
"呢些|這些%zhe4 xie5%/these/",
"我們呢一家|我們這一家%Atashin'chi",
"我的呢一班|我的這一班%Head of the Class",
"瞧！呢個人|瞧！這個人%Ecce Homo",
"呢是我的國家|這是我的國家%This Is My Country",
"呢醜陋又美麗的世界|這醜陋又美麗的世界%This Ugly Yet Beautiful World",
"些|啲",
"啲許|些許%xie1 xu3%/trifling/",
"那|嗰",
"到嗰裡|到那裡%dao4 na4 li3%/thither/",
"拉嗰烈|拉那烈%la1 na1 lie4%/(Prince) Ranariddh (son of King Sihanouk of Cambodia)/",
"嗰鴻書|那鴻書%na4 hong2 shu1%/Book of Nahum/",
"嗰裡|那裡%na4 li5%/there/that place/",
"嗰麼|那麼%na4 me5%/so (much)/like that/",
"嗰末|那末%na4 mo4%/if that's the case, then (...)/",
"嗰兒|那兒%nar3%/where/",
"嗰兒|那兒%nar4%/there/",
"嗰些|那些%na4 xie1%/those/",
"嗰樣|那樣%na4 yang4%/that kind/that sort/",
"嗰樣的|那樣的%na4 yang4 de5%/that kind of/that sort of/",
"嗰個|那個%nei4 ge4%/that one/",
"丹尼爾·嗰森斯|丹尼爾·那森斯%Daniel Nathans",
"亞他嗰修|亞他那修%Pope Athanasius I of Alexandria",
"亞利桑嗰大學|亞利桑那大學%University of Arizona",
"亞利桑嗰州|亞利桑那州%Arizona",
"亞利桑嗰州歷史|亞利桑那州歷史%History of Arizona",
"亞利桑嗰州議會大廈|亞利桑那州議會大廈%Arizona State Capitol",
"亞利桑嗰響尾蛇|亞利桑那響尾蛇%Arizona Diamondbacks",
"亞拉嗰斯|亞拉那斯%Aranarth",
"亞爾-阿登嗰霍|亞爾-阿登那霍%Ar-Adûnakhôr",
"亞述嗰西爾帕一世|亞述那西爾帕一世%Ashur-nasir-pal I",
"京嗰巴魯山|京那巴魯山%Mount Kinabalu",
"信嗰談比·拉惹勒南|信那談比·拉惹勒南%S. Rajaratnam",
"列奧西·揚嗰切克|列奧西·揚那切克%Leoš Janáček",
"加嗰利群島|加那利群島%Canary Islands",
"北卡羅萊嗰州|北卡羅萊那州%North Carolina",
"印度支嗰虎|印度支那虎%Indochinese Tiger",
"印第安嗰·瓊斯|印第安那·瓊斯%Indiana Jones",
"印第安嗰大學|印第安那大學%Indiana University",
"印第安嗰小馬|印第安那小馬%Indianapolis Colts",
"哈瓦嗰俱樂部|哈瓦那俱樂部%Havana Club",
"哈瓦嗰大學|哈瓦那大學%University of Havana",
"哈瓦嗰省|哈瓦那省%Havana Province",
"哈嗰德·玻爾|哈那德·玻爾%Harald Bohr",
"哈嗰鯊屬|哈那鯊屬%Broadnose sevengill shark",
"唐·史蒂芬·森納嗰亞克|唐·史蒂芬·森納那亞克%Don Stephen Senanayake",
"喬達摩菩提嗰加爾縣|喬達摩菩提那加爾縣%Gautam Buddha Nagar district",
"圭亞嗰元|圭亞那元%Guyanese dollar",
"圭亞嗰國旗|圭亞那國旗%Flag of Guyana",
"地拉嗰區|地拉那區%Tirana District",
"地拉嗰州|地拉那州%Tirana County",
"塔信·欽嗰瓦|塔信·欽那瓦%Thaksin Shinawatra",
"塔爾-安嗰瑞安|塔爾-安那瑞安%Tar-Anárion",
"塔爾-明嗰斯特|塔爾-明那斯特%Tar-Minastir",
"塔爾-阿塔嗰馬|塔爾-阿塔那馬%Tar-Atanamir",
"塔嗰嗰利彿|塔那那利彿%Antananarivo",
"安嗰波利斯|安那波利斯%Annapolis, Maryland",
"安嗰瑞安|安那瑞安%Anárion",
"安嗰罕天使球場|安那罕天使球場%Angel Stadium of Anaheim",
"安嗰翰|安那翰%Anaheim, California",
"安嗰翰鴨|安那翰鴨%Anaheim Ducks",
"安嗰託利亞|安那託利亞%Anatolia",
"安嗰託利亞語族|安那託利亞語族%Anatolian languages",
"寧嗰·華納·法斯賓德|寧那·華納·法斯賓德%Rainer Werner Fassbinder",
"少年印第安嗰瓊斯年譜|少年印第安那瓊斯年譜%The Young Indiana Jones Chronicles",
"居嗰加德縣|居那加德縣%Junagadh district",
"岡瓦嗰大陸|岡瓦那大陸%Gondwana",
"巴塞羅嗰伯爵|巴塞羅那伯爵%List of Counts of Barcelona",
"巴塞羅嗰足球俱樂部|巴塞羅那足球俱樂部%FC Barcelona",
"巴夫嗰加爾|巴夫那加爾%Bhavnagar",
"巴夫嗰加爾縣|巴夫那加爾縣%Bhavnagar district",
"巴拉嗰河|巴拉那河%Paraná River",
"帕嗰辛納克體育場|帕那辛納克體育場%Panathinaiko Stadium",
"恩森嗰達|恩森那達%Ensenada, Baja California",
"拉嗰烈親王|拉那烈親王%Norodom Ranariddh",
"拘屍嗰羅|拘屍那羅%Kushinagar",
"拿嗰克|拿那克%Guru Nanak Dev",
"斐波嗰喫數列|斐波那喫數列%Fibonacci number",
"斯利嗰加|斯利那加%Srinagar",
"斯堪的嗰維亞語支|斯堪的那維亞語支%North Germanic languages",
"普嗰卡|普那卡%Punakha",
"本嗰比|本那比%Burnaby, British Columbia",
"本嗰比市議會|本那比市議會%Burnaby City Council",
"格蘭嗰再也綫|格蘭那再也綫%Kelana Jaya Line",
"梭發嗰·富馬親王|梭發那·富馬親王%Souvanna Phouma",
"毗奢耶嗰伽羅王朝|毗奢耶那伽羅王朝%Vijayanagara Empire",
"毗盧遮嗰彿|毗盧遮那彿%Vairocana",
"氯苯嗰敏|氯苯那敏%chlorphenamine",
"波斯尼亞黑塞哥維嗰國旗|波斯尼亞黑塞哥維那國旗%Flag of Bosnia and Herzegovina",
"洛杉磯安嗰罕天使|洛杉磯安那罕天使%Los Angeles Angels of Anaheim",
"溴苯嗰敏|溴苯那敏%Brompheniramine",
"烏拉嗰拉·阿巴亥|烏拉那拉·阿巴亥%Abahai",
"熱嗰亞|熱那亞%Genoa",
"熱嗰亞共和國|熱那亞共和國%Republic of Genoa",
"熱嗰亞足球俱樂部|熱那亞足球俱樂部%Genoa C.F.C.",
"玻嗰病毒科|玻那病毒科%borna disease",
"米嗰斯伊西爾|米那斯伊西爾%Minas Morgul",
"米嗰斯提力斯|米那斯提力斯%Minas Tirith",
"緊嗰羅|緊那羅%Kinnara",
"考嗰斯|考那斯%Kaunas",
"耆嗰教|耆那教%jainism",
"耆嗰龍|耆那龍%Jainosaurus",
"與嗰原町|與那原町%Yonabaru, Okinawa",
"與嗰國島|與那國島%Yonaguni",
"與嗰國町|與那國町%Yonaguni, Okinawa",
"蓋亞嗰太空中心|蓋亞那太空中心%Guiana Space Centre",
"薩爾嗰加|薩爾那加%Xel'Naga",
"蘇仁德拉嗰加縣|蘇仁德拉那加縣%Surendranagar district",
"西地嗰非|西地那非%sildenafil",
"西西裡和嗰不勒斯君主列表|西西裡和那不勒斯君主列表%List of monarchs of Naples and Sicily",
"託馬斯·斯特爾嗰斯·艾略特|託馬斯·斯特爾那斯·艾略特%T. S. Eliot",
"路易斯安嗰州|路易斯安那州%Louisiana",
"辛辛嗰堤|辛辛那堤%Cincinnati, Ohio",
"辛辛嗰堤／北肯塔基國際機場|辛辛那堤／北肯塔基國際機場%Cincinnati/Northern Kentucky International Airport",
"辛辛嗰提孟加拉虎|辛辛那提孟加拉虎%Cincinnati Bengals",
"辛辛嗰提紅人|辛辛那提紅人%Cincinnati Reds",
"達嗰埃|達那埃%Danaë",
"嗰不勒斯|那不勒斯%Naples",
"嗰伊阿得斯|那伊阿得斯%naiad",
"嗰加蘭邦|那加蘭邦%nagaland",
"嗰卡西|那卡西%Nakasi",
"嗰慕爾|那慕爾%Namur",
"嗰慕爾省|那慕爾省%Namur",
"嗰曲地區|那曲地區%Nagqu Prefecture",
"嗰木巴爾·恩赫巴亞爾|那木巴爾·恩赫巴亞爾%Nambaryn Enkhbayar",
"嗰格浦爾|那格浦爾%nagpur",
"嗰楚克·巴嘎班迪|那楚克·巴嘎班迪%Natsagiin Bagabandi",
"嗰波尼德|那波尼德%Nabonidus",
"嗰洛六法|那洛六法%Six Yogas of Naropa",
"嗰爛陀寺|那爛陀寺%Nalanda",
"嗰爾邁|那爾邁%Narmer",
"嗰爾馬達縣|那爾馬達縣%Narmada district",
"嗰空拍儂府|那空拍儂府%Nakhon Phanom Province",
"嗰英|那英%Na Ying",
"嗰霸機場|那霸機場%Naha Airport",
"嗰須與一|那須與一%Nasu no Yoichi",
"嗰鴻書|那鴻書%Book of Nahum",
"錫嗰羅亞州|錫那羅亞州%Sinaloa",
"關塔嗰摩灣|關塔那摩灣%Guantanamo Bay Naval Base",
"關塔嗰摩省|關塔那摩省%Guantánamo Province",
"阿嗰克薩哥拉|阿那克薩哥拉%Anaxagoras",
"阿嗰克西曼德|阿那克西曼德%Anaximander",
"阿嗰克西美尼|阿那克西美尼%Anaximenes of Miletus",
"阿嗰含|阿那含%anagami",
"雅典嗰哥拉|雅典那哥拉%Athenagoras of Athens",
"雅坦嗰塔一世|雅坦那塔一世%Atanatar I",
"非嗰西丁|非那西丁%phenacetin",
"馬赫薩嗰縣|馬赫薩那縣%Mehsana district",
"黑塞哥維嗰-涅雷特瓦州|黑塞哥維那-涅雷特瓦州%Herzegovina-Neretva Canton",
"亞利桑嗰龍|亞利桑那龍%Arizonasaurus",
"努嗰福特|努那福特%Nunavut",
"哈瓦嗰舊城|哈瓦那舊城%Old Havana",
"安嗰蘇|安那蘇%Anusol",
"寶乍文·欽嗰瓦|寶乍文·欽那瓦%Potjaman Shinawatra",
"支嗰人|支那人%Shinajin",
"東區尤德夫人嗰打素醫院|東區尤德夫人那打素醫院%Pamela Youde Nethersole Eastern Hospital",
"波斯尼亞和黑塞哥維嗰社會主義共和國|波斯尼亞和黑塞哥維那社會主義共和國%Socialist Republic of Bosnia and Herzegovina",
"烏拉嗰拉·舒蘭|烏拉那拉·舒蘭%Empress Jing Xian",
"納木嗰尼峰|納木那尼峰%Gurla Mandhata",
"紗嗰村|紗那村%Kurilsk",
"耆嗰教|耆那教%Fasting in Jainism",
"莫嗰魯道|莫那魯道%Mona Rudao",
"辛辛嗰提黑旅|辛辛那提黑旅%Black Brigade of Cincinnati",
"嗰拉氏|那拉氏%Nara",
"嗰曲縣|那曲縣%Nagqu County",
"嗰薩嗰姆阿賈克斯足球俱樂部|那薩那姆阿賈克斯足球俱樂部%FC Ajax Lasnamäe",
"嗰霸市|那霸市%Naha, Okinawa",
"錯嗰縣|錯那縣%Cona County",
"關塔嗰摩灣|關塔那摩灣%Guantánamo Bay",
"雅麗氏何妙齡嗰打素醫院|雅麗氏何妙齡那打素醫院%Alice Ho Miu Ling Nethersole Hospital",
"鬱久閭嗰蓋|鬱久閭那蓋%Yujiulü Nagai",
"鬱久閭阿嗰瓌|鬱久閭阿那瓌%Yujiulü Anagui",
"怎|點",
"不點麼|不怎麼%bu4 zen3 me5%/not very/not particularly/",
"不點麼樣|不怎麼樣%bu4 zen3 me5 yang4%/not up to much/very indifferent/",
"點麼|怎麼%zen3 me5%/(interrogative pronoun)/how (can it be that)/",
"點麼樣|怎麼樣%zen3 me5 yang4%/how about/(used in the negative)(not) so good/",
"點樣|怎樣%zen3 yang4%/how/why/",
"看|睇",
"睇不見|看不見%kan4 bu2 jian4%/unseen/",
"睇待|看待%kan4 dai4%/look upon/regard/",
"睇守者|看守者%kan4 shou3 zhe3%/watchman/",
"睇板|看板%kanban",
"瞬間睇地球|瞬間看地球%EarthTV",
"沒|冇",
"被冇收|被沒收%bei4 mo4 shou1%/forfeit/",
"從來冇有|從來沒有%cong2 lai2 mei2 you3%/have",
"幾乎冇有|幾乎沒有%ji1 hu1 mei2 you3%/scarcely/hardly any/",
"冇有|沒有%mei2 you3%/haven't/hasn't/doesn't exist/to not have/to not be/",
"冇有必要|沒有必要%mei2 you3 bi4 yao4%/there is no need to (do sth)/",
"冇有差別|沒有差別%mei2 you3 cha1 bie2%/there is no difference/it makes no difference/",
"冇有聯繫|沒有聯繫%mei2 you3 lian2 xi4%/to be unrelated/",
"冇有人|沒有人%mei2 you3 ren2%/nobody/",
"冇有生育能力|沒有生育能力%mei2 you3 sheng1 yu4 neng2 li4%/infertile/unable to have children/",
"冇有什麼|沒有什麼%mei2 you3 shen2 me5%/there's nothing (... about it)/",
"冇有形狀|沒有形狀%mei2 you3 xing2 zhuang4%/shapeless/",
"冇有知覺|沒有知覺%mei2 you3 zhi1 jue2%/insensible/",
"冇落|沒落%mo4 luo4%/downfall/",
"冇收|沒收%mo4 shou1%/confiscate/",
"四不一冇有|四不一沒有%Four Noes and One Without",
"沉冇成本|沉沒成本%sunk cost",
"冇收|沒收%confiscation",
"冇有銀彈|沒有銀彈%No Silver Bullet",
"冇藥|沒藥%myrrh",
"波蘭冇有滅亡|波蘭沒有滅亡%Dąbrowski's Mazurka",
"隱冇帶|隱沒帶%subduction",
"四要一冇有|四要一沒有%Four Wants and One Without",
"冇有共產黨就冇有新中國|沒有共產黨就沒有新中國%Without the Communist Party, There Would Be No New China",
"他|佢",
"其佢的人|其他的人%qi1 ta1 de5 ren2%/other people/",
"佢們|他們%ta1 men5%/they/",
"佢們都|他們都%ta1 men5 dou1%/all of them/",
"佢們自己|他們自己%ta1 men2 zi4 ji3%/themselves/",
"佢人|他人%ta1 ren2%/other person/someone else/",
"維佢命|維他命%wei2 ta1 ming4%/vitamin/",
"猶佢州|猶他州%you2 ta1 zhou1%/Utah/",
"亞佢那修|亞他那修%Pope Athanasius I of Alexandria",
"佢儂·吉滴卡宗|他儂·吉滴卡宗%Thanom Kittikachorn",
"佢加祿語|他加祿語%Tagalog language",
"佢彼河|他彼河%Tapi River, Thailand",
"佢與她的事情|他與她的事情%Kare Kano",
"利佢主義|利他主義%altruism",
"加蘭佢敏|加蘭他敏%galantamine",
"北達科佢州|北達科他州%North Dakota",
"南達科佢州|南達科他州%South Dakota",
"博佢侖府|博他侖府%Phatthalung Province",
"吉佢手|吉他手%guitarist",
"吉佢變調夾|吉他變調夾%capo",
"大巽佢群島|大巽他群島%Greater Sunda Islands",
"奧司佢韋|奧司他韋%oseltamivir",
"奧洛佢定|奧洛他定%Olopatadine",
"小巽佢群島|小巽他群島%Lesser Sunda Islands",
"巽佢海峽|巽他海峽%Sunda Strait",
"拿弗佢利|拿弗他利%Naphtali",
"木佢龍|木他龍%Muttaburrasaurus",
"漁夫和佢的妻子|漁夫和他的妻子%the fisherman and his wife",
"猶佢大學|猶他大學%University of Utah",
"猶佢州|猶他州%utah",
"猶佢爵士隊|猶他爵士隊%Utah Jazz",
"猶佢盜龍|猶他盜龍%Utahraptor",
"猶佢縣|猶他縣%Utah County, Utah",
"猶佢-阿茲特克語系|猶他-阿茲特克語系%Uto-Aztecan languages",
"禁止在海底和洋底及其下面設置核武器和其佢大規模毀滅性武器條約|禁止在海底和洋底及其下面設置核武器和其他大規模毀滅性武器條約%Seabed Arms Control Treaty",
"禁止酷刑和其佢殘忍、不人道或有辱人格的待遇或處罰公約|禁止酷刑和其他殘忍、不人道或有辱人格的待遇或處罰公約%United Nations Convention Against Torture",
"維佢斯·白令|維他斯·白令%Vitus Bering",
"蒙西拉米·瑪希敦·納阿育佢耶王儲妃|蒙西拉米·瑪希敦·納阿育他耶王儲妃%Srirasmi",
"辛伐佢汀|辛伐他汀%simvastatin",
"達科佢縣|達科他縣%Dakota County",
"重要佢人|重要他人%significant other",
"阿託伐佢汀|阿託伐他汀%atorvastatin",
"頭孢佢啶|頭孢他啶%ceftazidime",
"馬爾佢十字|馬爾他十字%Maltese cross",
"馬爾佢騎士團|馬爾他騎士團%Sovereign Military Order of Malta",
"馬耳佢語|馬耳他語%Maltese language",
"馬耳佢足球聯賽|馬耳他足球聯賽%Football in Malta",
"馬裡士佢卡沙|馬裡士他卡沙%Balestier Khalsa FC",
"南達科佢級戰列艦|南達科他級戰列艦%South Dakota class battleship",
"戀愛維佢命|戀愛維他命%Suppli",
"猶佢老鷹|猶他老鷹%Utah Eagles",
"維佢奶|維他奶%Vitasoy",
"它|佢",
"德爾佢-2運載火箭|德爾它-2運載火箭%Delta II",
"她|姖",
"的|嘅",
"波羅嘅海|波羅的海%bo1 luo2 di4 hai3%/the Baltic Sea/",
"嘅確|的確%di2 que4%/really/indeed/",
"簡單嘅說|簡單的說%jian3 dan1 de5 shuo1%/to put it simply/simply put/",
"目嘅地|目的地%mu4 di4 di4%/destination (location)/",
"總嘅來說|總的來說%zong3 de5 lai2 shuo1%/generally speaking/to sum up/in summary/in short/",
"加嘅夫|加的夫%Cardiff",
"加嘅斯|加的斯%Cádiz",
"加嘅斯灣|加的斯灣%Gulf of Cádiz",
"加嘅斯省|加的斯省%Cádiz",
"加嘅斯足球俱樂部|加的斯足球俱樂部%Cádiz CF",
"士嘅數|士的數%Cabtaxi number",
"安嘅列斯群島|安的列斯群島%Antilles",
"小安嘅列斯群島|小安的列斯群島%Lesser Antilles",
"強嘅松|強的松%prednisone",
"怯嘅不花|怯的不花%Kitbuqa",
"波羅嘅海|波羅的海%Baltic Sea",
"波羅嘅海國家|波羅的海國家%Baltic states",
"波羅嘅海德國人|波羅的海德國人%Baltic Germans",
"波羅嘅語族|波羅的語族%Baltic languages",
"嘅嗒糖|的嗒糖%Tic tac",
"嘅士數|的士數%taxicab number",
"嘅嘅喀喀湖|的的喀喀湖%Lake Titicaca",
"嘅裡雅斯特|的裡雅斯特%Trieste",
"嘅黎波裡|的黎波裡%Tripoli",
"目嘅節點序列距離矢量協議|目的節點序列距離矢量協議%Destination-Sequenced Distance Vector routing",
"目嘅論|目的論%teleology",
"科嘅阿克島自治市鎮|科的阿克島自治市鎮%Kodiak Island Borough, Alaska",
"麗嘅呼聲|麗的呼聲%Associated-Rediffusion",
"不|唔",
"阿唔來提.阿唔都熱西提|阿不來提.阿不都熱西提%a1 bu4 lai2 ti2 a1 bu4 du1 re4 xi1 ti2%/Abdulaidi Amudurexiti (chairman of Xinjiang autonomous region)/",
"愛唔釋手|愛不釋手%ai4 bu4 shi4 shou3%/fondle admiringly/",
"愛理唔理|愛理不理%ai4 li3 bu4 li3%/look cold and indifferent/be standoffish/",
"按兵唔動|按兵不動%an4 bing3 bu4 dong4%/not throw the troops into battle/bide one's time/take on action/",
"巴唔得|巴不得%ba1 bu4 de2%/anxious/look forward to/earnestly wish for/",
"百讀唔厭|百讀不厭%bai3 du2 bu4 yan4%/be worth reading a hundred times/",
"百思唔解|百思不解%bai3 si1 bu4 jie3%/remain puzzled after pondering over sth/a hundred times/remain perplexed despite much thought/",
"百聽唔厭|百聽不厭%bai3 ting1 bu4 yan4%/worth hearing a hundred times/",
"百聞唔如一見|百聞不如一見%bai3 wen2 bu4 ru2 yi1 jian4%/seeing for oneself is a hundred times better than hearing from others/",
"百折唔撓|百折不撓%bai3 zhe2 bu4 nao2%/keep on fighting in spite of all setbacks/be undaunted by repeated setbacks/be indomitable/",
"百足之蟲死而唔僵|百足之蟲死而不僵%bai3 zu2 zhi1 chong2 si3 er2 bu4 jiang1%/a centipede dies but never falls down/old institutions die hard/",
"八九唔離十|八九不離十%ba1 jiu3 bu4 li2 shi2%/pretty close/very near/about right/",
"扳唔倒兒|扳不倒兒%ban1 bu4 dao3 er5%/tumbler/roly-poly/",
"抱唔平|抱不平%bao4 bu4 ping2%/be outraged by an injustice/",
"保唔住|保不住%bao3 bu2 zhu4%/most likely/more likely than not/may well/",
"備而唔用|備而不用%bei4 er2 bu4 yong4%/have something ready just in case/keep something for possible future use/",
"必唔可少|必不可少%bi4 bu4 ke3 shao3%/absolutely necessary/indispensable/essential/",
"必唔可少組成|必不可少組成%bi4 bu4 ke3 shao3 zu3 cheng2%/absolute necessity/sine qua non/",
"比唔上|比不上%bi3 bu4 shang4%/can't compare with/",
"兵唔厭詐|兵不厭詐%bin1 bu4 yan4 zha4%/there can never be too much deception in war/in war nothing is too deceitful/all's fair in war/",
"兵唔血刃|兵不血刃%bing1 bu4 sue4 ren4%/the edges of the swords not being stained with blood - win victory without firing a shot/",
"冰炭唔相容|冰炭不相容%bing1 tan4 bu4 xiang1 rong2%/as incompatible or irreconcilable as ice and hot coals/",
"並行唔悖|並行不悖%bing4 xing2 bu4 bei4%/both can be implemented without coming into conflict/not be mutually exclusive/run parallel/",
"比上唔足比下有余|比上不足比下有余%bi3 shang4 bu4 zu2 bi3 xia4 you3 yu2%/fall short of the best but be better than the worst/can pass muster/",
"唔安|不安%bu4 an1%/intranquil/unpeaceful/unstable/uneasy/disturbed/restless/worried/",
"唔敗之地|不敗之地%bu4 bai4 zhi1 di4%/invincible position/",
"唔白之冤|不白之冤%bu4 bai2 zhi1 yuan1%/unrighted wrong/unredressed injustice/",
"唔備|不備%bu4 bei4%/unprepared/off guard/",
"唔比|不比%bu4 bi3%/unlike/",
"唔必|不必%bu4 bi4%/need not/does not have to/",
"唔便|不便%bu4 bian4%/inconvenient/inappropriate/unsuitable/short of cash/",
"唔變|不變%bu4 bian4%/unchanging/constant/",
"唔變化|不變化%bu4 bian4 hua4%/invariably/",
"唔變價格|不變價格%bu4 bian4 jia4 ge2%/fixed price/constant price/",
"唔辨菽麥|不辨菽麥%bu4 bian4 shu1 mai4%/be unable to tell beans from wheat - have no knowledge of practical matters/",
"唔變資本|不變資本%bu4 bian4 zi1 ben3%/constant capital/",
"唔避艱險|不避艱險%bu4 bi4 jian1 xian3%/shrink or flinch from no difficulty or danger/make light of difficulties and dangers/",
"唔必要|不必要%bu2 bi4 yao4%/needless/unnecessary/",
"唔測|不測%bu4 ce4%/accident/mishap/contingency/",
"唔曾|不曾%bu4 ceng2%/never (have done sth/)/",
"唔成|不成%bu4 cheng2%/won't do/",
"唔成功|不成功%bu4 cheng2 gong1%/unsuccessful/",
"唔承認主義|不承認主義%bu4 cheng2 ren4 zhu3 yi4%/policy of nonrecognition/",
"唔誠實|不誠實%bu4 cheng2 shi2%/dishonest/",
"唔成文法|不成文法%bu4 cheng2 wen2 fa3%/unwritten law/",
"唔逞之徒|不逞之徒%bu4 cheng3 zhi1 tu2%/desperado/",
"唔啻|不啻%bu4 chi4%/not less than/as/like/as good as/",
"唔齒|不齒%bu4 chi3%/despise/hold in contempt/",
"唔恥下問|不恥下問%bu4 chi3 xia4 wen4%/not feel ashamed to ask and learn from one's subordinates/",
"唔揣冒昧|不揣冒昧%bu4 chuai3 mao4 mei4%/venture to/presume to/take the liberty of/",
"唔出所料|不出所料%bu4 chu1 suo3 liao4%/as expected/",
"唔辭而別|不辭而別%bu4 ci2 er2 bie2%/leave without saying good-bye/",
"唔辭辛苦|不辭辛苦%bu4 ci2 xin1 ku3%/make nothing of hardships/",
"唔錯|不錯%bu4 cuo4%/correct/right/not bad/pretty good/",
"唔大|不大%bu2 da4%/not very/not too/not often/",
"唔打唔相識|不打不相識%bu4 da3 bu4 xiang1 shi2%/from an exchange of blows friendship grows/no discord/no concord/",
"唔待說|不待說%bu4 dai4 shuo1%/needless to say/it goes without saying/",
"唔大離兒|不大離兒%bu4 da4 li2 er5%/pretty close/just about right/not bad/",
"唔丹|不丹%bu4 dan1%/Bhutan/",
"唔但|不但%bu4 dan4%/not only (... but also...)/",
"唔單|不單%bu4 dan1%/not the only/not merely/not simply/",
"唔當|不當%bu4 dang4%/unsuitable/improper/inappropriate/",
"唔當一回事|不當一回事%bu2 dang4 yi4 hui2 shi4%/not regard as a matter (of any importance)/",
"唔道德|不道德%bu4 dao4 de2%/immoral/",
"唔到黃河心唔死|不到黃河心不死%bu4 dao4 huang2 he2 xin1 bu4 si3%/not stop until one reaches the Huanghe River - not stop until one reaches one's goal/refuse to give up until all hope is gone/",
"唔倒翁|不倒翁%bu4 dao3 weng1%/tumbler/roly-poly/",
"唔打自招|不打自招%bu4 da3 zi4 zhao1%/confess without being pressed/make a confession without duress/",
"唔得|不得%bu4 de2%/must not/may not/not be allowed/cannot/",
"唔得而知|不得而知%bu4 de2 er2 zhi1%/unknown/unable to find out/",
"唔得勁|不得勁%bu4 de2 jin4%/awkward/unhandy/be indisposed/not feel well/",
"唔得了|不得了%bu4 de2 liao3%/desperately serious/disastrous/extremely/exceedingly/",
"唔等|不等%bu4 deng3%/to vary/to differ/depending/",
"唔等邊三角形|不等邊三角形%bu4 deng3 bian1 san1 jiao3 xing2%/scalene triangle/",
"唔登大雅之堂|不登大雅之堂%bu4 deng1 da4 ya3 zhi1 tang2%/not appeal to refined taste/be unrefined/be unpresentable/",
"唔等號|不等號%bu4 deng3 hao4%/sign of inequality/",
"唔等價交換|不等價交換%bu4 deng3 jia4 jiao1 huan4%/exchange of unequal values/",
"唔等式|不等式%bu4 deng3 shi4%/inequality/",
"唔得人心|不得人心%bu4 de2 ren2 xin1%/not enjoy popular support/be unpopular/",
"唔得要領|不得要領%bu4 de2 yao4 ling3%/fail to grasp the main points/",
"唔得已|不得已%bu4 de2 yi3%/act against one's will/have no alternative but to/have to/to have no choice/must/",
"唔迭|不迭%bu4 die2%/cannot cope/find it too much/incessantly/",
"唔抵抗主義|不抵抗主義%bu4 di3 kang4 zhu3 yi4%/policy of nonresistance/",
"唔定|不定%bu4 ding4%/indefinite/adventitious/indeterminate/",
"唔定詞|不定詞%bu2 ding4 ci2%/infinitive/",
"唔動|不動%bu4 dong4%/motionless/",
"唔動產|不動產%bu4 dong4 chan3%/real estate/immovable property/immovables/",
"唔凍港|不凍港%bu4 dong4 gang3%/ice-free port/open port/",
"唔動聲色|不動聲色%bu4 dong4 she1 se4%/maintain one's composure/stay calm and collected/not turn a hair/not bat an eyelid/",
"唔動搖|不動搖%bu4 dong4 yao2%/unmoved/",
"唔獨|不獨%bu4 du2%/not only/",
"唔端|不端%bu4 duan1%/improper/dishonourable/",
"唔斷|不斷%bu4 duan4%/unceasing/uninterrupted/continuous/constant/",
"唔對|不對%bu4 dui4%/incorrect/wrong/amiss/abnormal/queer/",
"唔對碴兒|不對碴兒%bu4 dui4 cha2 er5%/not proper/not fit for the occasion/",
"唔二法門|不二法門%bu4 er4 fa3 men2%/the one and only way/the only proper course to take/",
"唔乏|不乏%bu4 fa2%/there is no lack of/",
"唔法|不法%bu4 fa3%/lawless/illegal/unlawful/",
"唔凡|不凡%bu4 fan2%/out of the ordinary/out of the common run/",
"唔妨|不妨%bu4 fang1%/there is no harm in/might as well/",
"唔方便|不方便%bu4 fang1 bian4%/inconvenience/inconvenient/",
"唔費吹灰之力|不費吹灰之力%bu4 fei4 chui1 hui1 zhi1 li4%/as easy as blowing off dust - not needing the slightest effort/",
"唔分彼此|不分彼此%bu4 fen1 bi3 ci3%/make no distinction between what's one's own and what's another's/share everything/be on very intimate terms/",
"唔分青紅皂白|不分青紅皂白%bu4 fen1 qing1 hong2 zao4 bai2%/indiscriminately/",
"唔分勝負|不分勝負%bu4 fen1 sheng4 fu4%/tie/draw/come out even/",
"唔服|不服%bu4 fu2%/not accept (something)/want to have (something) overruled or changed/refuse to obey or comply/refuse to accept as final/remain unconvinced by/not give in to/",
"唔符|不符%bu4 fu2%/inconsistent/not in agreement with/not agree or tally with/not conform to/",
"唔服水土|不服水土%bu4 fu2 shui3 tu3%/(of a stranger) not accustomed to the climate of a new place/not acclimatized/",
"唔甘|不甘%bu4 gan1%/unreconciled to/not resigned to/unwilling/",
"唔干唔淨|不干不淨%bu4 gan1 bu4 jing4%/unclean/filthy/",
"唔敢當|不敢當%bu4 gan3 dang1%/you flatter me/I don't deserve it (your praise)/",
"唔干涉|不干涉%bu4 gan1 she4%/noninterference/nonintervention/",
"唔甘心|不甘心%bu4 gan1 xin1%/not reconciled to/not resigned to/",
"唔敢越雷池一步|不敢越雷池一步%bu4 gan3 yui4 lei2 chi2 yi1 bu4%/dare not go one step beyond the prescribed limit/",
"唔公|不公%bu4 gong1%/unjust/unfair/",
"唔恭|不恭%bu4 gong1%/disrespectful/",
"唔共戴天|不共戴天%bu4 gong4 dai4 tian1%/will not live under the same sky (with one's enemy) - absolutely irreconcilable/",
"唔公平|不公平%bu2 gong1 ping5%/unfair/",
"唔公正|不公正%bu4 gong1 zheng4%/injustice/",
"唔攻自破|不攻自破%bu4 gong1 zi4 po4%/collapse of itself/",
"唔苟|不苟%bu4 gou3%/not lax/not casual/careful/conscientious/",
"唔夠|不夠%bu4 gou4%/not enough/insufficient/inadequate/",
"唔顧|不顧%bu4 gu4%/in spite of/regardless of/",
"唔管|不管%bu4 guan3%/no matter (what, how)/regardless of/no matter/",
"唔光|不光%bu4 guang1%/not the only one/not only/",
"唔軌|不軌%bu4 gui3%/against the law or discipline/",
"唔規則|不規則%bu4 gui1 ze2%/irregular/",
"唔過|不過%bu4 guo4%/only/merely/no more than/but/however/only/",
"唔過爾爾|不過爾爾%bu4 guo4 er3 er3%/merely mediocre/just middling/",
"唔過意|不過意%bu4 guo4 yi4%/be sorry/feel apologetic/",
"唔顧一切|不顧一切%bu2 gu4 yi1 qie1%/reckless/",
"唔寒而慄|不寒而慄%bu4 han2 er2 li4%/shiver all over though not cold/tremble with fear/shudder/",
"唔含糊|不含糊%bu4 han2 hu1%/unambiguous/unequivocal/explicit/not ordinary/really good/",
"唔好|不好%bu4 hao3%/no good/",
"唔好惹|不好惹%bu4 hao3 re3%/not to be trifled with/not to be pushed around/stand no nonsense/",
"唔好意思|不好意思%bu4 hao3 yi4 si5%/feel embarrassed/be ill at ease/find it embarrassing (to do sth/)/",
"唔合|不合%bu4 he2%/not conform to/be unsuited to/be out of keeping with/should not/ought out/",
"唔和|不和%bu4 he2%/not get along well/be on bad terms/be at odds/discord/",
"唔合法|不合法%bu4 he2 fa3%/illegal/",
"唔合理|不合理%bu4 he2 li3%/unreasonable/",
"唔很|不很%bu4 hen3%/not very/",
"唔合適|不合適%bu4 he2 shi4%/improper/",
"唔懷好意|不懷好意%bu4 huai2 hao3 yi4%/harbour evil designs/harbour malicious intentions/",
"唔歡而散|不歡而散%bu4 huan1 er2 san4%/part on bad terms/(of a meeting/etc/) break up in discord/",
"唔會|不會%bu4 hui4%/improbable/unlikely/will not (act/happen/etc/)/have not learned to/be unable to/",
"唔諱|不諱%bu4 hui4%/without concealing anything/die/",
"唔及|不及%bu4 ji2%/not as good as/inferior to/find it too late/",
"唔濟|不濟%bu4 ji4%/not good/of no use/",
"唔羈|不羈%bu4 ji1%/unruly/uninhibited/",
"唔見|不見%bu4 jian4%/not see/not meet/",
"唔簡單|不簡單%bu4 jian3 dan1%/not simple/rather complicated/remarkable/marvellous/",
"唔見得|不見得%bu4 jian4 de5%/not necessarily/not likely/",
"唔見棺材唔落淚|不見棺材不落淚%bu4 jian4 guan1 cai2 bu4 luo4 lei4%/not shed a tear until one sees the coffin - refuse to be convinced until one is faced with grim reality/",
"唔見經傳|不見經傳%bu4 jian4 jing1 zhuan4%/not to be found in the classics - not authoritative/unknown/",
"唔見了|不見了%bu4 jian4 le5%/disappear/be missing/",
"唔加思索|不加思索%bu4 jia1 si1 suo3%/without thinking/without hesitation/readily/offhand/",
"唔即唔離|不即不離%bu4 ji2 bu4 li2%/be neither too familiar nor too distant/keep sb/at arm's length/",
"唔解|不解%bu4 jie3%/not understand/indissoluble/",
"唔結果|不結果%bu4 jie2 guo3%/fruitless/",
"唔結盟|不結盟%bu4 jie2 meng2%/nonalignment/",
"唔及格|不及格%bu4 ji2 ge2%/fail/",
"唔吉利|不吉利%bu4 ji2 li4%/ominous/",
"唔記名投票|不記名投票%bu4 ji4 ming2 tou2 piao4%/secret ballot/",
"唔僅|不僅%bu4 jin3%/not the only one/not only/not just/",
"唔禁|不禁%bu4 jin1%/can't help (doing sth/)/can't refrain from/",
"唔脛而走|不脛而走%bu4 jing4 er2 zou3%/get round fast/spread like wildfire/",
"唔景氣|不景氣%bu4 jing3 qi4%/depression/recession/slump/",
"唔經意|不經意%bu4 jing1 yi4%/carelessly/by accident/",
"唔經一事唔長一智|不經一事不長一智%bu4 jing1 yi1 zhi4 bu4 zhang3 yi1 zhi4%/you can't gain knowledge without practice/wisdom comes from experience/",
"唔經之談|不經之談%bu4 jing1 zhi1 tan2%/absurd statement/cock-and-bull story/",
"唔近人情|不近人情%bu4 jin4 ren2 qing2%/not amenable to reason/unreasonable/",
"唔計其數|不計其數%bu4 ji4 qi2 shu4%/countless/innumerable/",
"唔濟事|不濟事%bu4 ji4 shi4%/no good/of no use/not of any help/",
"唔久|不久%bu4 jiu3%/not long (after)/before too long/soon/soon after/",
"唔咎既往|不咎既往%bu4 jiu4 ji4 wang3%/not censure sb/for his past misdeeds/overlook sb's past mistakes/let bygones be bygones/",
"唔及物動詞|不及物動詞%bu4 ji2 wu4 dong4 ci2%/intransitive verb/",
"唔急之務|不急之務%bu4 ji2 zhi4 wu4%/a matter of no great urgency/",
"唔拘|不拘%bu4 ju1%/not stick to/not confine oneself to/whatever/",
"唔倦|不倦%bu4 juan4%/tireless/untiring/indefatigable/",
"唔覺察|不覺察%bu4 jue2 cha2%/unaware/",
"唔絕如縷|不絕如縷%bu4 jue2 ru2 lu3%/hanging by a thread/very precarious/almost extinct/(of sound) linger on faintly/",
"唔拘一格|不拘一格%bu4 ju1 yi1 ge2%/not stick to one pattern/",
"唔堪|不堪%bu4 kan1%/cannot bear/cannot stand/utterly/extremely/",
"唔亢唔卑|不亢不卑%bu4 kan4 bu4 bei1%/neither haughty nor humble/neither overbearing nor servile/neither supercilious nor obsequious/",
"唔堪忍受|不堪忍受%bu4 kan1 ren3 shou4%/unbearable/",
"唔可|不可%bu4 ke3%/cannot/should not/must not/",
"唔克|不克%bu2 ke4%/cannot/to not be able (to)/to be unable to/",
"唔可多得|不可多得%bu4 ke3 duo1 de2%/hard to come by/rare/",
"唔可分離|不可分離%bu4 ke3 fen1 li2%/inseparable/",
"唔可告人|不可告人%bu4 ke3 gao4 ren2%/hidden/kept secret/not to be divulged/",
"唔可估量|不可估量%bu4 ke3 gu1 liang4%/inestimable/incalculable/beyond measure/",
"唔可救藥|不可救藥%bu4 ke3 jiu4 yao4%/incurable/incorrigible/beyond cure/hopeless/",
"唔可抗力|不可抗力%bu4 ke3 kang4 li4%/force majeure/",
"唔可理喻|不可理喻%bu4 ke3 li3 yu4%/be impervious to reason/won't listen to reason/",
"唔可名狀|不可名狀%bu4 ke3 ming2 zhuang4%/indescribable/beyond description/",
"唔可磨滅|不可磨滅%bu4 ke3 mo2 mie4%/indelible/",
"唔可能|不可能%bu4 ke3 neng2%/impossible/",
"唔可能的事|不可能的事%bu4 ke3 neng2 de5 shi4%/impossibility/",
"唔客氣|不客氣%bu2 ke4 qi4%/you're welcome/impolite/rude/blunt/don't mention it/",
"唔可侵犯權|不可侵犯權%bu4 ke3 qin1 fan4 quan2%/inviolability/",
"唔可缺少|不可缺少%bu4 ke3 que1 shao3%/indispensable/",
"唔可勝數|不可勝數%bu4 ke3 sheng4 shu3%/countless/innumerable/",
"唔可收拾|不可收拾%bu4 ke3 shou1 shi2%/irremediable/unmanageable/out of hand/hopeless/",
"唔可思議|不可思議%bu4 ke3 si1 yi4%/inconceivable/unimaginable/",
"唔可同日而語|不可同日而語%bu4 ke3 tong2 ri4 er2 yu3%/cannot be mentioned in the same breath/",
"唔可一世|不可一世%bu4 ke3 yi1 shi4%/consider oneself unexcelled in the world/be insufferably arrogant/",
"唔可逾越|不可逾越%bu4 ke3 yu2 yue4%/impassable/insurmountable/insuperable/",
"唔可知論|不可知論%bu4 ke3 zhi1 lun4%/agnosticism/",
"唔可終日|不可終日%bu4 ke3 zhong1 ri4%/be unable to carry on even for a single day/be in a desperate situation/",
"唔快|不快%bu4 kuai4%/be unhappy/be displeased/be in low spirits/be indisposed/feel under the weather/be out of sorts/",
"唔愧|不愧%bu4 kui4%/be worthy of/deserve to be called/prove oneself to be/",
"唔賴|不賴%bu4 lai4%/not bad/good/fine/",
"唔勞而獲|不勞而獲%bu4 lao2 er2 huo4%/reap without sowing/profit by other people's toil/",
"唔力|不力%bu4 li4%/not do one's best/not exert oneself/",
"唔利|不利%bu4 li4%/unfavourable/disadvantageous/harmful/detrimental/",
"唔理|不理%bu4 li3%/refuse to acknowledge/pay no attention to/take no notice of/ignore/",
"唔良|不良%bu4 liang2%/bad/harmful/unhealthy/",
"唔稂唔莠|不稂不莠%bu4 liang2 bu4 you3%/useless/worthless/good-for-nothing/",
"唔了|不了%bu4 liao3%/unable to/without end/",
"唔料|不料%bu4 liao4%/unexpectedly/to one's surprise/",
"唔了了之|不了了之%bu4 liao3 liao3 zhi1%/settle a matter by leaving it unsettled/end up with nothing definite/",
"唔列顛諸島|不列顛諸島%bu2 lie4 dian1 zhu1 dao3%/British Isles/",
"唔離兒|不離兒%bu4 li2 er5%/not bad/pretty good/pretty close/",
"唔吝|不吝%bu4 lin4%/not stint/",
"唔靈|不靈%bu4 ling2%/not work/be ineffective/",
"唔論|不論%bu2 lun4%/no matter (what, who, how, etc.)/whether ... or .../regardless of/",
"唔論|不論%bu4 lun4%/no matter (what, who, how, etc.)/whether/or/regardless of/",
"唔倫唔類|不倫不類%bu4 lun2 bu4 lei4%/neither fish nor fowl/nondescript/",
"唔落窠臼|不落窠臼%bu4 luo4 ke1 jiu4%/not follow the beaten track/have an original style/",
"唔露聲色|不露聲色%bu4 lu4 sheng1 se4%/not show one's feeling/intentions/etc//",
"唔買賬|不買賬%bu4 mai3 zhang4%/not buy it/not go for it/",
"唔滿|不滿%bu4 man3%/resentful/discontented/dissatisfied/",
"唔忙|不忙%bu4 mang2%/there's no hurry/take one's time/",
"唔毛|不毛%bu4 mao2%/barren/",
"唔毛之地|不毛之地%bu4 mao2 zhi1 di4%/barren land/desert/",
"唔免|不免%bu4 mian3%/unavoidable/",
"唔妙|不妙%bu4 miao4%/(of a turn of events) not too encouraging/far from good/anything but reassuring/",
"唔明|不明%bu4 ming2%/not clear/unknown/fail to understand/",
"唔明確|不明確%bu4 ming2 que4%/indefinite/",
"唔名數|不名數%bu4 ming2 shu4%/abstract number/",
"唔名一文|不名一文%bu4 ming2 yi1 wen2%/without a penny to one's name/penniless/stony-broke/",
"唔名譽|不名譽%bu4 ming2 yu4%/disreputable/disgraceful/",
"唔名譽事物|不名譽事物%bu4 ming2 yu4 shi4 wu4%/dishonor/",
"唔摸頭|不摸頭%bu4 mo1 tou2%/not acquainted with the situation/not up on things/",
"唔謀而合|不謀而合%bu4 mou2 er2 he2%/agree without prior consultation/happen to hold the same view/",
"唔耐煩|不耐煩%bu2 nai4 fan2%/impatience/impatient/",
"唔能|不能%bu4 neng2%/cannot/must not/should not/",
"唔能抵抗|不能抵抗%bu4 neng2 di3 kang4%/irresistible/",
"唔怕|不怕%bu2 pa4%/fearless/",
"唔偏唔倚|不偏不倚%bu4 pian1 bu4 yi3%/even-handed/impartial/unbiased/",
"唔平|不平%bu4 ping2%/injustice/unfairness/wrong/grievance/indignant/resentful/",
"唔平常|不平常%bu4 ping2 chang2%/remarkable/remarkably/unusual/",
"唔平等條約|不平等條約%bu4 ping2 deng3 tiao2 yue1%/unequal treaty/",
"唔平凡|不平凡%bu4 ping2 fan2%/marvellous/marvellously/",
"唔平衡|不平衡%bu4 ping2 heng2%/disequilibrium/",
"唔平則鳴|不平則鳴%bu4 ping2 ze2 ming2%/where there is injustice/there will be an outcry/man will cry out against injustice/",
"唔破唔立|不破不立%bu4 po4 bu4 li4%/without destruction there can be no construction/",
"唔巧|不巧%bu4 qiao3%/unfortunately/as luck would have it/",
"唔期而遇|不期而遇%bu4 qi1 er2 yu4%/meet by chance/have a chance encounter/",
"唔切實際|不切實際%bu4 qie4 shi2 ji4%/unrealistic/unpractical/impracticable/",
"唔情願|不情願%bu4 qing2 yuan4%/unwilling/",
"唔情之請|不情之請%bu4 qing2 zhi1 qing3%/my presumptuous request/",
"唔期然而然|不期然而然%bu4 qi1 ran2 er2 ran2%/happen unexpectedly/turn out contrary to one's expectations/",
"唔求甚解|不求甚解%bu4 qiu2 shen4 jie3%/not seek to understand things thoroughly/be content with superficial understanding/",
"唔屈|不屈%bu4 qu1%/unyielding/unbending/",
"唔屈唔撓|不屈不撓%bu4 qu1 bu4 nao2%/unyielding/indomitable/",
"唔確定|不確定%bu4 que4 ding4%/uncertainty/",
"唔確實|不確實%bu4 que4 shi2%/untrue/",
"唔然|不然%bu4 ran2%/not so/no/or else/otherwise/if not/",
"唔然的話|不然的話%bu4 ran2 de5 hua4%/otherwise/",
"唔仁|不仁%bu4 ren2%/not benevolent/heartless/numb/",
"唔忍|不忍%bu4 ren3%/cannot bear to/",
"唔人道|不人道%bu4 ren2 dao4%/inhuman/",
"唔日|不日%bu4 ri4%/within the next few days/in a few days time/",
"唔容|不容%bu4 rong2%/not tolerate/not allow/not brook/not admit/",
"唔如|不如%bu4 ru2%/not equal to/not as good as/inferior to/it would be better to/",
"唔入虎穴焉得虎子|不入虎穴焉得虎子%bu4 ru4 hu3 xue2 yan1 de2 hu3 zi3%/how can you catch tiger cubs without entering the tiger's lair/nothing venture/nothing to gain or have/",
"唔三唔四|不三不四%bu4 san1 bu4 si4%/dubious/shady/neither one thing nor the other/neither fish nor fowl/nondescript/",
"唔善|不善%bu4 shan4%/bad/ill/not good at/not to be poohpoohed/quite impressive/",
"唔少|不少%bu4 shao3%/not (just) a few/",
"唔勝|不勝%bu4 sheng4%/cannot bear or stand/be unequal to/very/extremely/",
"唔勝枚舉|不勝枚舉%bu4 sheng4 mei2 ju3%/too numerous to mention individually or one by one/",
"唔時|不時%bu4 shi2%/frequently/often/at any time/",
"唔適|不適%bu4 shi4%/unwell/indisposed/out of sorts/",
"唔適當|不適當%bu4 shi4 dang4%/inadequate/unfit/",
"唔識大體|不識大體%bu4 shi2 da4 ti3%/fail to see the larger issues/ignore the general interest/",
"唔失時機|不失時機%bu4 shi1 shi2 ji1%/seize the opportune moment/lose no time/",
"唔識時務|不識時務%bu4 shi2 shi2 wu4%/show no understanding of the times/",
"唔識抬舉|不識抬舉%bu4 shi2 tai2 ju3%/fail to appreciate sb/'s kindness/not know how to appreciate favors/",
"唔是玩兒的|不是玩兒的%bu4 shi4 wan2 er5 de5%/it's no joke/",
"唔失為|不失為%bu4 shi1 wei2%/can still be considered (to be...)/may after all be accepted as/",
"唔是味兒|不是味兒%bu4 shi4 wei4 er5%/not the right flavour/not quite right/a bit off/fishy/queer/amiss/feel bad/be upset/",
"唔適用|不適用%bu4 shi4 yong4%/not applicable/NA/",
"唔時之需|不時之需%bu4 shi2 zhi1 xu1%/a possible period of want or need/",
"唔受歡迎|不受歡迎%bu4 shou4 huan1 ying2%/unwelcome/",
"唔受理|不受理%bu4 shou4 li3%/reject a complaint/refuse to entertain (a proposal)/",
"唔爽|不爽%bu4 shuang3%/not well/out of sorts/in a bad mood/without discrepancy/accurate/",
"唔舒適|不舒適%bu4 shu1 shi4%/uncomfortable/",
"唔死心|不死心%bu4 si3 xin1%/unwilling to give up/unresigned/",
"唔送|不送%bu4 song4%/don't bother to see me out/",
"唔送氣|不送氣%bu4 song4 qi4%/unaspirated/",
"唔遂|不遂%bu4 sui4%/fail/fail to materialize/",
"唔碎玻璃|不碎玻璃%bu4 sui4 bo1 li5%/shatterproof or safety glass/",
"唔隨意肌|不隨意肌%bu4 sui2 ji4 ji1%/involuntary muscle/",
"唔速之客|不速之客%bu4 su4 zhi1 ke4%/uninvited or unexpected guest/",
"唔特|不特%bu4 te4%/not only/",
"唔調和|不調和%bu4 tiao2 he2%/discord/",
"唔體面|不體面%bu4 ti3 mian4%/shameful/",
"唔停|不停%bu4 ting2%/incessant/",
"唔聽命|不聽命%bu4 ting1 ming4%/disobey/",
"唔同|不同%bu4 tong2%/different/distinct/not the same/not alike/",
"唔通|不通%bu4 tong1%/be obstructed/be blocked up/be impassable/not make sense/be illogical/be ungrammatical/",
"唔痛唔痒|不痛不痒%bu4 tong4 bu4 yang3%/scratching the surface/superficial/perfunctory/",
"唔同凡響|不同凡響%bu4 tong2 fan2 xiang3%/outstanding/out of the ordinary/out of the common run/",
"唔同意|不同意%bu4 tong2 yi4%/disagree/",
"唔透明|不透明%bu4 tou4 ming2%/opaque/",
"唔透氣|不透氣%bu4 tou4 qi4%/airtight/",
"唔透水|不透水%bu4 tou4 shui3%/waterproof/watertight/impermeable/",
"唔妥|不妥%bu4 tuo3%/not proper/inappropriate/",
"唔吐氣|不吐氣%bu4 tu3 qi4%/unaspirated/",
"唔外|不外%bu4 wai4%/not beyond the scope of/nothing more than/",
"唔完美|不完美%bu4 wan2 mei3%/defective/imperfect/",
"唔完全葉|不完全葉%bu4 wan2 quan2 ye4%/incomplete leaf/",
"唔完全中立|不完全中立%bu4 wan2 quan2 zhong1 li4%/imperfect neutrality/",
"唔完善|不完善%bu4 wan2 shan4%/imperfect/",
"唔惟|不惟%bu4 wei2%/not only/",
"唔違農時|不違農時%bu4 wei2 nong2 shi2%/not miss the farming season/do farm work in the right season/",
"唔為已甚|不為已甚%bu4 wei2 yi3 shen4%/refrain from going to extremes in meting out punishment/not be too hard on subject/",
"唔問|不問%bu4 wen4%/pay no attention to/disregard/ignore/let go unpunished/let off/",
"唔聞唔問|不聞不問%bu4 wen2 bu4 wen4%/not bother to ask questions or listen to what's said/show no interest in sth//be indifferent to something/",
"唔穩定氣流|不穩定氣流%bu4 wen3 ding4 qi4 liu2%/turbulent/",
"唔穩平衡|不穩平衡%bu4 wen3 ping2 heng2%/unstable equilibrium/",
"唔無小補|不無小補%bu4 wu2 xiao3 bu3%/not be without some advantage/be of some help/",
"唔務正業|不務正業%bu4 wu4 zhen4 ye4%/not engage in honest work/ignore one's proper occupation/not attend to one's proper duties/",
"唔惜|不惜%bu4 xi1%/not stint/not spare/not hesitate (to do sth/)/not scruple (to do sth/)/",
"唔暇|不暇%bu4 xia2%/have no time (for sth/)/be too busy (to do sth/)/",
"唔祥|不祥%bu4 xiang2%/ominous/inauspicious/",
"唔詳|不詳%bu4 xiang2%/not in detail/not quite clear/",
"唔相干|不相干%bu4 xiang1 gan1%/be irrelevant/have nothing to do with/",
"唔像話|不像話%bu4 xiang4 hua4%/unreasonable/shocking/outrageous/",
"唔相容|不相容%bu4 xiang1 rong2%/incompatible/",
"唔相上下|不相上下%bu4 xiang1 shang4 xia4%/equally matched/about the same/",
"唔像樣|不像樣%bu4 xiang4 yang4%/in no shape to be seen/unpresentable/beyond recognition/",
"唔肖|不肖%bu4 xiao4%/unworthy/",
"唔小心|不小心%bu4 xiao3 xin1%/heedless/uncareful/",
"唔下于|不下于%bu4 xia4 yu2%/as many as/no less than/not inferior to/as good as/on a par with/",
"唔屑|不屑%bu4 xie4%/disdain to do sth//think sth/not worth doing/feel it beneath one's dignity to do something/",
"唔懈|不懈%bu4 xie4%/untiring/unremitting/indefatigable/",
"唔謝|不謝%bu4 xie4%/don't mention it/not at all/",
"唔行|不行%bu4 xing2%/won't do/be out of the question/be no good/not work/not be capable/",
"唔幸|不幸%bu4 xing4%/misfortune/adversity/unfortunate/sad/unfortunately/",
"唔興|不興%bu4 xing1%/out of fashion/outmoded/impermissible/can't/",
"唔幸的是|不幸的是%bu2 xing4 de5 shi4%/unfortunately/",
"唔行了|不行了%bu4 xing2 le5%/on the point of death/dying/",
"唔省人事|不省人事%bu4 xing3 ren2 shi4%/be unconscious/be in a coma/",
"唔幸之事|不幸之事%bu4 xing4 zhi1 shi4%/mishap/",
"唔信任|不信任%bu4 xin4 ren4%/mistrust/",
"唔信任案|不信任案%bu4 xin4 ren4 an4%/no-confidence motion/",
"唔信任投票|不信任投票%bu4 xin4 ren4 tou2 piao4%/vote of no-confidence/",
"唔新鮮|不新鮮%bu4 xin1 xian1%/stale/",
"唔信用|不信用%bu4 xin4 yong4%/distrust/",
"唔休|不休%bu4 xiu1%/endlessly/ceaselessly/",
"唔朽|不朽%bu4 xiu3%/immortal/immortality/",
"唔修邊幅|不修邊幅%bu4 xiu1 bian1 fu2%/not care about one's appearance/be slovenly/",
"唔朽的|不朽的%bu4 xiu3 de5%/immortal/",
"唔鏽鋼|不鏽鋼%bu4 xiu4 gang1%/stainless steel/",
"唔許|不許%bu4 xu3%/not allow/must not/can't/",
"唔宣而戰|不宣而戰%bu4 xuan1 er2 zhan4%/open hostilities without declaring war/start an undeclared war/",
"唔虛此行|不虛此行%bu4 xu1 ci3 xing2%/the trip has not been made in vain/the trip has been well worthwhile/it's been a worthwhile trip/",
"唔學無術|不學無術%bu4 xue2 wu2 shu4%/have neither learning nor skill/be ignorant and incompetent/",
"唔遜|不遜%bu4 xun4%/rude/impertinent/",
"唔雅觀|不雅觀%bu4 ya3 guan1%/offensive to the eye/unbecoming/",
"唔厭|不厭%bu4 yan4%/not mind doing sth//not tire of/not object to/",
"唔言而喻|不言而喻%bu4 yan2 er2 yu4%/it goes without saying/it is self-evident/",
"唔遠千里|不遠千里%bu4 yan3 qian1 li3%/make light of travelling a thousand li/go to the trouble of travelling a long distance/",
"唔要|不要%bu4 yao4%/don't!/must not/",
"唔要緊|不要緊%bu4 yao4 jin3%/unimportant/not serious/it doesn't matter/never mind/it looks all right/but/",
"唔要臉|不要臉%bu4 yao4 lian3%/have no sense of shame/shameless/",
"唔一|不一%bu4 yi1%/vary/differ/",
"唔已|不已%bu4 yi3%/endlessly/incessantly/",
"唔依|不依%bu4 yi1%/not comply/not go along with/not let off easily/not let sb/get away with it/",
"唔宜|不宜%bu4 yi2%/not suitable/inadvisable/inappropriate/",
"唔意|不意%bu4 yi4%/unexpectedly/unawareness/unpreparedness/",
"唔翼而飛|不翼而飛%bu4 yi4 er2 fei1%/disappear without trace/vanish all of a sudden/spread fast/spread like wildfire/",
"唔一而足|不一而足%bu4 yi1 er2 zu2%/by no means an isolated case/numerous/",
"唔亦樂乎|不亦樂乎%bu4 yi4 le4 hu1%/extremely/awfully/",
"唔以為然|不以為然%bu4 yi3 wei2 ran2%/object to/take exception to/not approve/",
"唔遺余力|不遺余力%bu4 yi2 yu2 li4%/spare no pains or effort/do one's utmost/",
"唔義之財|不義之財%bu4 yi4 zhi1 cai2%/ill-gotten wealth or gains/",
"唔易之論|不易之論%bu4 yi4 zhi1 lun4%/perfectly sound proposition/unalterable truth/irrefutable argument/",
"唔用|不用%bu4 yong4%/need not/",
"唔用謝|不用謝%bu4 yong4 xie4%/You're welcome/",
"唔由得|不由得%bu4 you2 de2%/can't help/cannot but/",
"唔由自主|不由自主%bu4 you2 zi4 zhu3%/can't help/involuntarily/",
"唔予|不予%bu4 yu2%/not grant/",
"唔虞|不虞%bu4 yu2%/unexpected/eventuality/contingency/not worry about/",
"唔約而同|不約而同%bu4 yue1 er2 tong2%/take the same action or view without prior consultation/happen to coincide/",
"唔愉快|不愉快%bu4 yu2 kuai4%/disagreeable/unpleasant/",
"唔育性|不育性%bu4 yu4 xing4%/sterility/",
"唔育症|不育症%bu4 yu4 zheng4%/sterility/barrenness/",
"唔再|不再%bu4 zai4%/no more/no longer/",
"唔在|不在%bu4 zai4%/not be in/be out/",
"唔在乎|不在乎%bu4 zai4 hu1%/not mind/not care/",
"唔在話下|不在話下%bu4 zai4 hua4 xia4%/be nothing difficult/be a cinch/",
"唔在了|不在了%bu4 zai4 le5%/be dead/",
"唔在意|不在意%bu4 zai4 yi4%/pay no attention to/take no notice of/not mind/negligent/careless/",
"唔贊成|不贊成%bu4 zan4 cheng2%/disapproval/disapprove/",
"唔贊一詞|不贊一詞%bu4 zan4 yi1 ci2%/keep silent/make no comment/",
"唔怎麼|不怎麼%bu4 zen3 me5%/not very/not particularly/",
"唔怎麼樣|不怎麼樣%bu4 zen3 me5 yang4%/not up to much/very indifferent/",
"唔擇手段|不擇手段%bu4 ze2 shou3 duan4%/by fair means or foul/by hook or by crook/unscrupulously/",
"唔戰唔和|不戰不和%bu4 zhan4 bu4 he2%/no war/no peace/",
"唔折唔扣|不折不扣%bu4 zhe2 bu4 kou4%/a hundred per cent/to the letter/out-and-out/",
"唔正常|不正常%bu4 zheng4 chang2%/abnormal/",
"唔正常狀況|不正常狀況%bu4 zheng4 chang2 zhuang4 kuang4%/abnormal state/",
"唔爭氣|不爭氣%bu4 zheng1 qi4%/be disappointing/fail to live up to expectations/",
"唔正之風|不正之風%bu4 zheng4 zhi1 feng1%/unhealthy tendency/",
"唔止|不止%bu4 zhi3%/incessantly/without end/more than/not limited to/",
"唔只|不只%bu4 zhi3%/not only/not merely/",
"唔知|不知%bu4 zhi1%/unknowing(ly)/",
"唔值|不值%bu4 zhi2%/not worth/",
"唔智|不智%bu4 zhi4%/unwise/",
"唔知唔覺|不知不覺%bu4 zhi1 bu4 jue2%/unconsciously/unwittingly/",
"唔值得|不值得%bu4 zhi2 de5%/unworthy/",
"唔知凡幾|不知凡幾%bu4 zhi1 fan2 ji3%/can't tell how many there are - there are numerous similar cases/",
"唔知好歹|不知好歹%bu4 zhi1 hao3 dai3%/not know what's good for one/",
"唔知何故|不知何故%bu4 zhi1 he2 gu4%/somehow/",
"唔置可否|不置可否%bu4 zhi4 ke3 fou3%/decline to comment/not express an opinion/be noncommittal/hedge/",
"唔知死活|不知死活%bu4 zhi1 si4 huo2%/act recklessly/",
"唔知所措|不知所措%bu4 zhi1 suo3 cuo4%/be at a loss/be at one's wits' end/",
"唔知所云|不知所云%bu4 zhi1 suo3 yun2%/not know what sb/is driving at/be unintelligible/",
"唔知天高地厚|不知天高地厚%bu4 zhi1 tian1 gao1 di4 hou4%/not know the immensity of heaven and earth - have an exaggerated opinion of one's abilities/",
"唔至於|不至於%bu4 zhi4 yu2%/cannot go so far/be unlikely/",
"唔治之症|不治之症%bu4 zhi4 zhi1 zheng4%/incurable disease/",
"唔重視|不重視%bu4 zhong4 shi4%/indifference/",
"唔重要|不重要%bu4 zhong4 yao4%/unimportant/",
"唔中意|不中意%bu4 zhong1 yi4%/not to one's liking/",
"唔中用|不中用%bu4 zhong1 yong4%/unfit for anything/no good/useless/",
"唔周延|不周延%bu4 zhou1 yan2%/undistributed/",
"唔住|不住%bu2 zhu4%/repeatedly/continuously/constantly/",
"唔准|不准%bu4 zhun3%/not allow/forbid/prohibit/",
"唔著邊際|不著邊際%bu4 zhuo2 bian1 ji4%/not to the point/wide of the mark/neither here nor there/irrelevant/",
"唔著陸飛行|不著陸飛行%bu4 zhuo2 lu4 fei1 xing2%/nonstop flight/",
"唔注意|不注意%bu4 zhu4 yi4%/thoughtless/not pay attention to/",
"唔貲|不貲%bu4 zi1%/immeasurable/incalculable/",
"唔自量|不自量%bu2 zi4 liang4%/not take a proper measure of oneself/overrate one's own abilities/",
"唔自然|不自然%bu4 zi4 ran2%/unnatural/",
"唔自在|不自在%bu2 zi4 zai4%/uneasiness/",
"唔足|不足%bu4 zu2%/insufficient/lacking/deficiency/not enough/inadequate/not worth/cannot/should/",
"唔做聲|不做聲%bu4 zuo4 sheng1%/keep silent/not say a word/",
"唔足為訓|不足為訓%bu4 zu2 wei2 xun4%/not to be taken as an example/not an example to be followed/not to be taken as authoritative/",
"層出唔窮|層出不窮%ceng2 chu1 bu4 qiong2%/to come out one after the other/",
"差唔多|差不多%cha4 bu5 duo1%/almost, nearly/",
"吃唔服|吃不服%chi1 bu5 fu2%/not be accustomed to eating sth//not be used to certain food/",
"吃唔開|吃不開%chi1 bu5 kai1%/be unpopular/won't work/",
"吃唔來|吃不來%chi1 bu5 lai2%/not be fond of certain food/",
"吃唔上|吃不上%chi1 bu5 shang4%/be unable to get something to eat/miss a meal/",
"持唔同政見|持不同政見%chi2 bu4 tong2 zheng4 jian4%/(politically) dissenting/dissident/",
"持唔同政見者|持不同政見者%chi2 bu4 tong2 zheng4 jian4 zhe3%/(political) dissident/",
"吃唔下|吃不下%chi1 bu5 xia4%/not feel like eating/be unable to eat any more/",
"吃唔消|吃不消%chi1 bu5 xiao1%/be unable to stand (exertion/fatigue etc/)/",
"吃唔住|吃不住%chi1 bu5 zhu4%/be unable to bear or support/",
"喘唔過氣來|喘不過氣來%chuan3 bu2 guo4 qi4 lai2%/cannot breathe/",
"從容唔迫|從容不迫%cong2 rong2 bu4 po4%/calm/unruffled/",
"寸草唔生|寸草不生%cun4 cao3 bu4 sheng1%/'not even a blade of grass grows'/",
"達唔到|達不到%da2 bu4 dao4%/cannot achieve/cannot reach/",
"打唔過|打不過%da3 bu5 guo4%/not to be able to beat or defeat sb./to be no match for/",
"大惑唔解|大惑不解%da4 huo4 bu4 jie3%/do not understand a certain thing/",
"得唔到|得不到%de2 bu4 dao4%/cannot get/cannot obtain/",
"喋喋唔休|喋喋不休%die2 die2 bu4 xiu1%/chatter/",
"對唔起|對不起%dui4 bu4 qi4%/I'm sorry/pardon me/forgive me/",
"而唔需|而不需%er2 bu4 xu1%/without needing (to so sth)/",
"犯唔著|犯不著%fan2 bu5 zhao2%/not worthwhile/",
"憤憤唔平|憤憤不平%fen4 fen4 bu4 ping2%/indignant/",
"趕唔上|趕不上%gan3 bu4 shang4%/can't keep up with/can't catch up with/",
"怪唔得|怪不得%guai4 bu5 de5%/no wonder/",
"過唔去|過不去%guo4 bu5 qu4%/make life difficult for/embarrass/can't make it through/",
"核唔擴散|核不擴散%he2 bu4 kuo4 san4%/nuclear nonproliferation/",
"會唔會|會不會%hui4 bu4 hui4%/(posing a question: whether someone, something) can or not/is able to or not/",
"見唔得|見不得%jian4 bu5 de2%/may not be seen by or exposed to/",
"堅定唔移|堅定不移%jian1 ding4 bu4 yi2%/unswerving/unflinching/",
"堅忍唔拔|堅忍不拔%jian1 ren3 bu4 ba2%/fortitude/",
"看唔見|看不見%kan4 bu2 jian4%/unseen/",
"來唔及|來不及%lai2 bu5 ji2%/there's not enough time (to do sth.)/it's too late (to do sth.)/",
"目前還唔清楚|目前還不清楚%mu4 qian2 hai2 bu4 qing1 chu3%/at present it is still unclear ..../",
"迫唔得已|迫不得已%po4 bu4 de2 yi3%/have no choice/compelled/",
"前唔久|前不久%qian2 bu4 jiu3%/not long before/",
"誓唔反悔|誓不反悔%shi4 bu4 fan3 hui3%/to vow not to break one's promise/",
"是唔是|是不是%shi4 bu4 shi4%/is or isn't/yes or no/whether or not/",
"視而唔見|視而不見%shi4 er2 bu4 jian4%/turn a blind eye to/",
"誓死唔降|誓死不降%shi4 si3 bu4 xiang2%/to vow to fight to the death/",
"數唔盡|數不盡%shu4 bu2 jin4%/countless/",
"數唔清|數不清%shu3 bu4 qing1%/countless/",
"說唔出話來|說不出話來%shuo1 bu4 chu1 hua4 lai2%/speechless/",
"說唔定|說不定%shuo1 bu5 ding4%/can't say for sure/maybe/",
"死唔了|死不了%si3 bu4 liao3%/Portulaca Sundial (a type of plant)/",
"微唔足道|微不足道%wei1 bu4 zu2 dao4%/negligible/insignificant/",
"無所唔賣|無所不賣%wu2 suo3 bu2 mai4%/to sell anything/to sell everything/",
"無所唔能|無所不能%wu2 suo3 bu4 neng2%/omnipotent/",
"無所唔在|無所不在%wu2 suo3 bu4 zai4%/omnipresent/",
"無所唔知|無所不知%wu2 suo3 bu4 zhi1%/omniscient/",
"行唔通|行不通%xing2 bu5 tong1%/won't work/will get (you) nowhere/",
"形影唔離|形影不離%xing2 ying3 bu4 li2%/inseparable (as form and shadow)/",
"意見唔合|意見不合%yi4 jian4 bu4 he2%/dissension/",
"意想唔到|意想不到%yi4 xiang3 bu4 dao4%/unexpected/previously unimagined/",
"願意唔願意|願意不願意%yuan4 yi4 bu2 yuan4 yi4%/whether one wants to or not/",
"找唔到|找不到%zhao3 bu4 dao4%/couldn't find/",
"只唔過幾年前|只不過幾年前%zhi3 bu4 guo4 ji3 nian2 qian2%/only a few years ago/just a few years ago/",
"直言唔諱|直言不諱%zhi2 yan2 bu4 hui4%/speak frankly and bluntly/",
"一個都唔能少|一個都不能少%Not One Less",
"三唔政策|三不政策%Three Noes",
"三角唔等式|三角不等式%triangle inequality",
"下唔列顛|下不列顛%Britannia Inferior",
"唔丹|不丹%Bhutan",
"唔丹國家足球隊|不丹國家足球隊%Bhutan national football team",
"唔丹國徽|不丹國徽%Emblem of Bhutan",
"唔丹國旗|不丹國旗%Flag of Bhutan",
"唔丹國王|不丹國王%List of rulers of Bhutan",
"唔丹外交|不丹外交%Foreign relations of Bhutan",
"唔丹經濟|不丹經濟%Economy of Bhutan",
"唔二論|不二論%Advaita Vedanta",
"唔交並|不交並%disjoint union",
"唔交集|不交集%disjoint sets",
"唔來梅大學|不來梅大學%University of Bremen",
"唔來梅州|不來梅州%Bremen",
"唔來梅的城市樂手|不來梅的城市樂手%Town Musicians of Bremen",
"唔依賴空氣推進|不依賴空氣推進%Air-independent propulsion",
"唔信任動議|不信任動議%motion of no confidence",
"唔倫瑞克|不倫瑞克%Braunschweig",
"唔倫瑞克縣|不倫瑞克縣%Brunswick County, North Carolina",
"唔公正抽籤|不公正抽籤%Kujibiki Unbalance",
"唔列顛印度軍隊|不列顛印度軍隊%British Indian Army",
"唔列顛哥倫比亞|不列顛哥倫比亞%British Columbia",
"唔列顛哥倫比亞大學|不列顛哥倫比亞大學%University of British Columbia",
"唔列顛哥倫比亞省省議會|不列顛哥倫比亞省省議會%Legislative Assembly of British Columbia",
"唔列顛尼亞號|不列顛尼亞號%HMY Britannia",
"唔列顛帝國勳章|不列顛帝國勳章%Order of the British Empire",
"唔列顛東印度公司|不列顛東印度公司%Honourable East India Company",
"唔列顛空戰|不列顛空戰%Battle of Britain",
"唔列顛群島|不列顛群島%British Isles",
"唔動產|不動產%real estate",
"唔動產投資信託|不動產投資信託%Real estate investment trust",
"唔動點|不動點%Fixed point",
"唔動點組合子|不動點組合子%fixed point combinator",
"唔可兒戲|不可兒戲%The Importance of Being Earnest",
"唔可化約的複雜性|不可化約的複雜性%irreducible complexity",
"唔可思議星球的雙胞胎公主|不可思議星球的雙胞胎公主%Fushigiboshi no Futagohime",
"唔可抗力|不可抗力%force majeure",
"唔可數集|不可數集%uncountable set",
"唔可知論|不可知論%agnosticism",
"唔可能的三位一體|不可能的三位一體%impossible trinity",
"唔問，唔說|不問，不說%Don't ask, don't tell",
"唔在地主所有權|不在地主所有權%landed property",
"唔完全類型|不完全類型%partial class",
"唔定積分|不定積分%antiderivative",
"唔平等條約|不平等條約%unequal treaties",
"唔擴散核武器條約|不擴散核武器條約%Nuclear Non-Proliferation Treaty",
"唔敗的戀人|不敗的戀人%Bubai de Lianren",
"唔明潛水物|不明潛水物%unidentified submerged object",
"唔明飛行物|不明飛行物%unidentified flying object",
"唔朽之都：尼羅河的兒女|不朽之都：尼羅河的兒女%Immortal Cities: Children of the Nile",
"唔死三振|不死三振%uncaught third strike",
"唔死生物|不死生物%undead",
"唔治之症|不治之症%terminal illness",
"唔消費日|不消費日%Buy Nothing Day",
"唔潔淨的動物|不潔淨的動物%unclean animals",
"唔當得利|不當得利%unjust enrichment",
"唔知火舞|不知火舞%Mai Shiranui",
"唔破郡|不破郡%Fuwa District, Gifu",
"唔確定性|不確定性%uncertainty",
"唔確定性原理|不確定性原理%uncertainty principle",
"唔空|不空%Amoghavajra",
"唔等|不等%inequality",
"唔管部大臣|不管部大臣%minister without portfolio",
"唔結盟運動|不結盟運動%Non-Aligned Movement",
"唔規則星繫|不規則星繫%irregular galaxy",
"唔設防城市|不設防城市%Rome, Open City",
"唔變子空間|不變子空間%invariant subspace",
"唔變子空間問題|不變子空間問題%invariant subspace problem",
"唔賽因|不賽因%Abu Sa'id",
"唔鏽鋼|不鏽鋼%stainless steel",
"唔間斷電源|不間斷電源%uninterruptible power supply",
"唔飽和烴|不飽和烴%unsaturated hydrocarbon",
"唔齊線數字|不齊線數字%text figures",
"中蘇互唔侵犯條約|中蘇互不侵犯條約%Sino-Soviet Non-Aggression Pact",
"乳糖唔耐症|乳糖不耐症%lactose intolerance",
"了唔起的蓋茨比|了不起的蓋茨比%The Great Gatsby",
"互唔侵犯原則|互不侵犯原則%non-aggression principle",
"京都唔死鳥|京都不死鳥%Kyoto Sanga F.C.",
"人口唔足|人口不足%population decline",
"伯努利唔等式|伯努利不等式%Bernoulli's inequality",
"佩多唔等式|佩多不等式%Pedoe's inequality",
"信息唔對稱|信息不對稱%information asymmetry",
"光州尚武唔死鳥|光州尚武不死鳥%Gwangju Sangmu Phoenix",
"克拉夫特唔等式|克拉夫特不等式%Kraft's inequality",
"內斯比特唔等式|內斯比特不等式%Nesbitt's inequality",
"再生唔良性貧血|再生不良性貧血%aplastic anemia",
"切比雪夫總和唔等式|切比雪夫總和不等式%Chebyshev's sum inequality",
"動詞唔定式|動詞不定式%infinitive",
"去/唔去|去/不去%go/no go",
"呂唔韋|呂不韋%Lü Buwei",
"哥德爾唔完備定理|哥德爾不完備定理%Gödel's incompleteness theorems",
"單元唔飽和脂肪|單元不飽和脂肪%monounsaturated fat",
"四唔一沒有|四不一沒有%Four Noes and One Without",
"多元唔飽和脂肪|多元不飽和脂肪%polyunsaturated fat",
"大唔列顛島|大不列顛島%Great Britain",
"大唔列顛旗幟列表|大不列顛旗幟列表%List of British flags",
"大唔列顛王國|大不列顛王國%Kingdom of Great Britain",
"大唔列顛與愛爾蘭聯合王國|大不列顛與愛爾蘭聯合王國%United Kingdom of Great Britain and Ireland",
"大唔裡士|大不裡士%tabriz",
"孫唔二|孫不二%Sun Bu'er",
"射後唔理|射後不理%fire-and-forget",
"小唔點|小不點%The Littles",
"小野唔由美|小野不由美%Fuyumi Ono",
"已唔存在國家列表|已不存在國家列表%List of extinct states",
"帶點與唔帶點I|帶點與不帶點I%Turkish dotted and dotless I",
"平均數唔等式|平均數不等式%inequality of arithmetic and geometric means",
"幾何唔穩定性|幾何不穩定性%geometrical frustration",
"延森唔等式|延森不等式%Jensen's inequality",
"心急吃唔了熱豆腐|心急吃不了熱豆腐%Eat Hot Tofu Slowly",
"怯的唔花|怯的不花%Kitbuqa",
"愛情，唔用尋找|愛情，不用尋找%Broken Flowers",
"成骨唔全症|成骨不全症%osteogenesis imperfecta",
"我為什麼唔是基督徒|我為什麼不是基督徒%Why I Am Not a Christian",
"手氣唔錯|手氣不錯%I'm Feeling Lucky",
"持唔同政見者|持不同政見者%dissident",
"持唔同政見者列表|持不同政見者列表%List of Chinese dissidents",
"排序唔等式|排序不等式%rearrangement inequality",
"新唔了情|新不了情%C'est la vie, mon chéri",
"新唔列顛|新不列顛%New Britain",
"新鐵金剛之唔日殺機|新鐵金剛之不日殺機%Die Another Day",
"日唔落帝國|日不落帝國%The empire on which the sun never sets",
"星條旗永唔落|星條旗永不落%Stars and Stripes Forever",
"時唔變系統|時不變系統%Time-invariant system",
"曾獲唔列顛帝國勳章人士名單|曾獲不列顛帝國勳章人士名單%List of celebrities who have been awarded the Order of the British Empire",
"最小唔動點|最小不動點%least fixed point",
"杜興氏肌肉營養唔良症|杜興氏肌肉營養不良症%Duchenne muscular dystrophy",
"東新唔列顛省|東新不列顛省%east new britain",
"柯西-施瓦兹唔等式|柯西-施瓦兹不等式%Cauchy–Schwarz inequality",
"桃樂絲·恩唔裡居|桃樂絲·恩不裡居%Dolores Umbridge",
"樊畿唔等式|樊畿不等式%Ky Fan inequality",
"泡利唔相容原理|泡利不相容原理%Pauli exclusion principle",
"注意力唔足過動症|注意力不足過動症%ADHD predominantly inattentive",
"海綿狀腦白質營養唔良症|海綿狀腦白質營養不良症%Canavan disease",
"營養唔良|營養不良%malnutrition",
"牢唔可破的聯盟|牢不可破的聯盟%National Anthem of the Soviet Union",
"狗唔理包子|狗不理包子%Goubuli",
"瑞斯丁娜，或喻美德的唔幸|瑞斯丁娜，或喻美德的不幸%The Misfortunes of Virtue",
"生命中唔能承受之輕|生命中不能承受之輕%The Unbearable Lightness of Being",
"申唔害|申不害%Shen Buhai",
"社會唔平等|社會不平等%economic inequality",
"禁止酷刑和其他殘忍、唔人道或有辱人格的待遇或處罰公約|禁止酷刑和其他殘忍、不人道或有辱人格的待遇或處罰公約%United Nations Convention Against Torture",
"笑傲江湖之東方唔敗|笑傲江湖之東方不敗%Swordsman II",
"籐原唔比等|籐原不比等%Fujiwara no Fuhito",
"籐子唔二雄|籐子不二雄%Fujiko Fujio",
"絕熱唔變量|絕熱不變量%adiabatic invariant",
"線性時唔變系統理論|線性時不變系統理論%LTI system theory",
"美索唔達米亞|美索不達米亞%Mesopotamia",
"義唔容情|義不容情%Looking Back in Anger",
"腦白質營養唔良|腦白質營養不良%leukodystrophy",
"荒誕唔經的故事|荒誕不經的故事%tall tale",
"莫氏唔連續面|莫氏不連續面%Mohorovičić discontinuity",
"藥物唔良反應|藥物不良反應%adverse drug reaction",
"蘇德互唔侵犯條約|蘇德互不侵犯條約%Molotov-Ribbentrop Pact",
"複數選區單記唔可讓渡投票制|複數選區單記不可讓渡投票制%single non-transferable vote",
"西西裡和那唔勒斯君主列表|西西裡和那不勒斯君主列表%List of monarchs of Naples and Sicily",
"要食物唔要炸彈|要食物不要炸彈%Food Not Bombs",
"速唔臺|速不臺%Subutai",
"那唔勒斯|那不勒斯%Naples",
"鄧唔利多的軍隊|鄧不利多的軍隊%Dumbledore's Army",
"長生唔老|長生不老%immortality",
"閔可夫斯基唔等式|閔可夫斯基不等式%Minkowski inequality",
"阿唔思·鄧唔利多|阿不思·鄧不利多%Albus Dumbledore",
"阿達馬唔等式|阿達馬不等式%Hadamard's inequality",
"阿里唔哥|阿里不哥%Ariq Boke",
"飛馬座矮唔規則星繫|飛馬座矮不規則星繫%Pegasus Dwarf Irregular Galaxy",
"魯唔魯乞|魯不魯乞%William of Rubruck",
"唔丹外交|不丹外交%Bhutanese diplomatic missions",
"唔丹足球甲級聯賽|不丹足球甲級聯賽%A-Division",
"唔來梅|不來梅%bremen",
"唔來梅市政廳|不來梅市政廳%Bremen City Hall",
"唔來梅沙洲體育俱樂部|不來梅沙洲體育俱樂部%SV Werder Bremen",
"唔動產|不動產%Real estate transfer tax",
"唔在場證明|不在場證明%alibi",
"唔穿內褲咖啡廳|不穿內褲咖啡廳%No-pan kissa",
"唔織布|不織布%nonwovens",
"唔義管家的比喻|不義管家的比喻%Parable of the Unjust Steward",
"唔能結婚的男人|不能結婚的男人%Kekkon Dekinai Otoko",
"唔能說的秘密|不能說的秘密%Secret",
"唔降|不降%Bu Jiang of Xia",
"唔需要愛情的夏天|不需要愛情的夏天%Love Me Not",
"千杯唔醉|千杯不醉%Drink-Drank-Drunk",
"國際唔再恐同日|國際不再恐同日%International Day Against Homophobia",
"執迷唔悔|執迷不悔%No Regrets",
"天使唔設防!|天使不設防!%I'm Gonna Be An Angel!",
"宇文丘唔勤|宇文丘不勤%Yuwen Qiubuqin",
"寧鳴唔默|寧鳴不默%Keep Not Silent",
"對唔起、我愛你|對不起、我愛你%I'm Sorry, I Love You",
"已唔存在的NBA球隊列表|已不存在的NBA球隊列表%List of defunct National Basketball Association teams",
"東方唔敗|東方不敗%Master Asia",
"矮唔規則星繫|矮不規則星繫%Dwarf irregular galaxy",
"積極唔干預|積極不干預%Positive non-interventionism",
"英雄唔再|英雄不再%No More Heroes",
"計算機唔能做什麼|計算機不能做什麼%What Computers Can't Do",
"金斯唔穩定性|金斯不穩定性%Jeans instability",
"雷頓教授與唔可思議城鎮|雷頓教授與不可思議城鎮%Professor Layton and the Curious Village",
"她|姖",
"姖自己|她自己%ta1 zi4 ji3%/herself/",
"怹|佢",
"牠|佢",
"是|係",
"搬弄係非|搬弄是非%ban1 nong4 shi4 fei1%/sow discord/tell tales/make mischief/",
"係否|是否%shi4 fou3%/whether (or not)/if/is or isn't/",
"伊係名村|伊是名村%Izena, Okinawa",
"我們係冠軍|我們是冠軍%We Are the Champions",
"係枝裕和|是枝裕和%Hirokazu Koreeda",
"查拉圖斯特拉如係說|查拉圖斯特拉如是說%Thus Spoke Zarathustra",
"神係中學生|神是中學生%Kamichu!",
"高橋係清|高橋是清%Takahashi Korekiyo",
"了|咗",
"不咗咗之|不了了之%bu4 liao3 liao3 zhi1%/settle a matter by leaving it unsettled/end up with nothing definite/",
"咗解|了解%liao3 jie3%/understand/come to understand/find out/",
"投咗票|投了票%tou2 le5 piao4%/past tense of to vote/",
"直截咗當|直截了當%zhi2 jie2 liao3 dang4%/plain-talking/blunt/straightforward/",
"咗不起的蓋茨比|了不起的蓋茨比%The Great Gatsby",
"新不咗情|新不了情%C'est la vie, mon chéri",
"淺井咗意|淺井了意%Asai Ryōi",
"來|嚟",
"阿不嚟提.阿不都熱西提|阿不來提.阿不都熱西提%a1 bu4 lai2 ti2 a1 bu4 du1 re4 xi1 ti2%/Abdulaidi Amudurexiti (chairman of Xinjiang autonomous region)/",
"本嚟面目|本來面目%ben3 lai2 mian4 mu4%/true colours/true features/",
"從嚟不|從來不%cong2 lai2 bu4%/never/",
"從嚟沒有|從來沒有%cong2 lai2 mei2 you3%/have",
"從外表嚟看|從外表來看%cong2 wai4 biao3 lai2 kan4%/looking from the outside/seen from the outside/",
"讀者嚟信|讀者來信%du2 zhe3 lai2 xin4%/Reader's Letters/",
"反過嚟說|反過來說%fan3 guo4 lai2 shuo1%/on the other hand/",
"即將嚟臨|即將來臨%ji2 jiang1 lai2 lin2%/imminent/",
"舉例嚟說|舉例來說%ju3 li4 lai2 shuo1%/for example/",
"嚟不及|來不及%lai2 bu5 ji2%/there's not enough time (to do sth.)/it's too late (to do sth.)/",
"嚟到|來到%lai2 dao4%/to come/to arrive/",
"嚟訪|來訪%lai2 fang3%/pay a visit/",
"嚟福槍|來福槍%lai2 fu2 qiang1%/rifle/",
"嚟回嚟去地|來回來去地%lai2 hui2 lai2 qu4 de5%/backwards and forwards/",
"嚟歷|來歷%lai2 li4%/history/antecendents/origin/",
"嚟臨|來臨%lai2 lin2%/approach/come closer/",
"嚟年|來年%lai2 nian2%/next year/the coming year/",
"嚟往|來往%lai2 wang3%/to come and go/",
"嚟源|來源%lai2 yuan2%/source (of information, etc)/origin/",
"嚟自|來自%lai2 zi4%/to come from (a place)/",
"歷嚟最低點|歷來最低點%li4 lai2 zui4 di1 dian3%/all time low (point)/",
"馬嚟人|馬來人%ma3 lai2 ren2%/Malaysian person or people/",
"馬嚟文|馬來文%ma3 lai2 wen2%/Malasian (language)/",
"馬嚟西亞|馬來西亞%ma3 lai2 xi1 ya4%/Malasia/",
"馬嚟西亞語|馬來西亞語%ma3 lai2 xi1 ya4 yu3%/Malasian (language)/",
"馬嚟語|馬來語%ma3 lai2 yu3%/Malaysian language/",
"外嚟投資|外來投資%wai4 lai2 tou2 zi5%/foreign investment/",
"希伯嚟書|希伯來書%xi1 bo2 lai2 shu1%/Hebrews/",
"希伯嚟語|希伯來語%xi1 bo2 lai2 yu3%/Hebrew (language)/",
"一般嚟說|一般來說%yi4 ban1 lai2 shuo1%/generally speaking/",
"又嚟了|又來了%you4 lai2 le5%/Here we go again/",
"越嚟越|越來越%yue4 lai2 yue4%/more and more/",
"越嚟越多|越來越多%yue4 lai2 yue4 duo1%/more and more/",
"越嚟越嚴重|越來越嚴重%yue4 lai2 yue4 yan2 zhong4%/to become more serious every day/",
"轉嚟轉去|轉來轉去%zhuan3 lai2 zhuan3 qu4%/rove around/",
"主要嚟源|主要來源%zhu3 yao4 lai2 yuan2%/principle source/main source/",
"總的嚟說|總的來說%zong3 de5 lai2 shuo1%/generally speaking/to sum up/in summary/in short/",
"一個陌生女子的嚟信|一個陌生女子的來信%Letter from an Unknown Woman",
"上海嚟的女人|上海來的女人%The Lady from Shanghai",
"不嚟梅大學|不來梅大學%University of Bremen",
"不嚟梅州|不來梅州%Bremen",
"不嚟梅的城市樂手|不來梅的城市樂手%Town Musicians of Bremen",
"亞瑞吉嚟布一世|亞瑞吉來布一世%Argeleb I",
"亞瑞吉嚟布二世|亞瑞吉來布二世%Argeleb II",
"伊妮·布嚟敦|伊妮·布來敦%Enid Blyton",
"嚟古格士|來古格士%Lycurgus",
"嚟弗歐克縣|來弗歐克縣%Live Oak County, Texas",
"嚟自天外|來自天外%Butsu Zone",
"倖田嚟未|倖田來未%Kumi Koda",
"全世界無產者，聯合起嚟！|全世界無產者，聯合起來！%Workers of the world, unite!",
"加嚟海峽省|加來海峽省%Pas-de-Calais",
"加嚟道雄|加來道雄%Michio Kaku",
"勞動帶嚟自由|勞動帶來自由%Arbeit macht frei",
"北卡羅嚟納大學教堂山分校|北卡羅來納大學教堂山分校%University of North Carolina at Chapel Hill",
"北卡羅嚟納大學系統|北卡羅來納大學系統%University of North Carolina",
"北卡羅嚟納級戰列艦|北卡羅來納級戰列艦%North Carolina class battleship",
"北部-加嚟海峽|北部-加來海峽%Nord-Pas de Calais",
"南卡羅嚟納州|南卡羅來納州%South Carolina",
"博嚟黴素|博來黴素%bleomycin",
"卡嚟卡|卡來卡%Karaikal",
"卡羅嚟納颶風隊|卡羅來納颶風隊%Carolina Hurricanes",
"唑嚟磷酸|唑來磷酸%zoledronate",
"喜嚟登酒店|喜來登酒店%Sheraton Hotels and Resorts",
"土著（馬嚟西亞）|土著（馬來西亞）%bumiputra",
"外嚟語|外來語%loanword",
"大西洋底嚟的人|大西洋底來的人%Man from Atlantis",
"如嚟藏|如來藏%Tathagatagarbha doctrine",
"布嚟德索縣|布來德索縣%Bledsoe County, Tennessee",
"希伯嚟人|希伯來人%Hebrews",
"希伯嚟協和學院|希伯來協和學院%Hebrew Union College",
"希伯嚟字母|希伯來字母%Hebrew alphabet",
"希伯嚟曆|希伯來曆%Hebrew calendar",
"希伯嚟書|希伯來書%Epistle to the Hebrews",
"希伯嚟語|希伯來語%Hebrew language",
"希伯嚟語維基百科|希伯來語維基百科%Hebrew Wikipedia",
"彿嚟明右手定則|彿來明右手定則%Fleming's right hand rule",
"彿嚟明左手定則/temp|彿來明左手定則/temp%Fleming's left hand rule",
"往嚟戶口|往來戶口%transactional account",
"得嚟速|得來速%drive-through",
"未嚟主義|未來主義%Category:Futurism",
"未嚟主義宣言|未來主義宣言%Futurist Manifesto",
"未嚟全球領袖|未來全球領袖%Global Leader of Tomorrow",
"未嚟學|未來學%futurology",
"東馬嚟西亞|東馬來西亞%East Malaysia",
"柏克嚟種植園|柏克來種植園%Berkeley Plantation",
"橫濱港未嚟21|橫濱港未來21%Minato Mirai 21",
"橫濱高速鐵道港未嚟線|橫濱高速鐵道港未來線%Minatomirai Line",
"死神嚟了|死神來了%Final Destination",
"港澳居民嚟往內地通行證|港澳居民來往內地通行證%home return permit",
"烏嚟鄉|烏來鄉%Wulai Township",
"狼嚟了|狼來了%The Boy Who Cried Wolf",
"男人嚟自火星，女人嚟自金星|男人來自火星，女人來自金星%Men Are from Mars, Women Are from Venus",
"當幸福嚟敲門|當幸福來敲門%The Pursuit of Happyness",
"禮嚟制藥公司|禮來制藥公司%Eli Lilly and Company",
"索嚟索語|索來索語%solresol",
"自嚟水|自來水%tap water",
"西馬嚟西亞|西馬來西亞%Peninsular Malaysia",
"金嚟沅|金來沅%Kim Rae Won",
"飛去嚟器|飛去來器%boomerang",
"馬嚟亞人民解放軍|馬來亞人民解放軍%Malayan Peoples' Liberation Army",
"馬嚟亞大學|馬來亞大學%University of Malaya",
"馬嚟亞銀行|馬來亞銀行%Maybank",
"馬嚟人至上|馬來人至上%Ketuanan Melayu",
"馬嚟半島|馬來半島%Malay Peninsula",
"馬嚟奕|馬來奕%Kuala Belait",
"馬嚟族|馬來族%Malays",
"馬嚟-波利尼西亞語族|馬來-波利尼西亞語族%Malayo-Polynesian languages",
"馬嚟熊|馬來熊%sun bear",
"馬嚟群島|馬來群島%Malay Archipelago",
"馬嚟西亞|馬來西亞%Malaysia",
"馬嚟西亞印度國大黨|馬來西亞印度國大黨%Malaysian Indian Congress",
"馬嚟西亞國家足球隊|馬來西亞國家足球隊%Malaysia national football team",
"馬嚟西亞國家銀行|馬來西亞國家銀行%Bank Negara Malaysia",
"馬嚟西亞國徽|馬來西亞國徽%Emblem of Malaysia",
"馬嚟西亞國旗|馬來西亞國旗%Flag of Malaysia",
"馬嚟西亞地理|馬來西亞地理%Geography of Malaysia",
"馬嚟西亞城市列表|馬來西亞城市列表%Cities of Malaysia",
"馬嚟西亞大獎賽|馬來西亞大獎賽%Malaysian Grand Prix",
"馬嚟西亞封啣|馬來西亞封啣%Malay titles",
"馬嚟西亞憲法第153條款|馬來西亞憲法第153條款%Article 153 of the Constitution of Malaysia",
"馬嚟西亞最高元首|馬來西亞最高元首%Yang di-Pertuan Agong",
"馬嚟西亞歷史|馬來西亞歷史%History of Malaysia",
"馬嚟西亞滙豐銀行有限公司|馬來西亞滙豐銀行有限公司%HSBC Bank Malaysia",
"馬嚟西亞經濟|馬來西亞經濟%Economy of Malaysia",
"馬嚟西亞航空|馬來西亞航空%Malaysia Airlines",
"馬嚟西亞航空653號班機|馬來西亞航空653號班機%Malaysia Airlines Flight 653",
"馬嚟西亞華人|馬來西亞華人%Malaysian Chinese",
"馬嚟西亞華人公會|馬來西亞華人公會%Malaysian Chinese Association",
"馬嚟西亞行政區劃|馬來西亞行政區劃%States of Malaysia",
"馬嚟西亞金杯|馬來西亞金杯%Malaysia Cup",
"馬嚟西亞電訊公司|馬來西亞電訊公司%Telekom Malaysia",
"馬嚟西亞首相|馬來西亞首相%Prime Minister of Malaysia",
"馬嚟語|馬來語%Malay language",
"馬嚟貘|馬來貘%Malayan Tapir",
"馬嚟酸|馬來酸%maleic acid",
"馬嚟長吻鱷|馬來長吻鱷%false gharial",
"高立的未嚟世界|高立的未來世界%Future Boy Conan",
"鬼子嚟了|鬼子來了%Devils on the Doorstep",
"不嚟梅|不來梅%bremen",
"不嚟梅市政廳|不來梅市政廳%Bremen City Hall",
"不嚟梅沙洲體育俱樂部|不來梅沙洲體育俱樂部%SV Werder Bremen",
"中國未嚟航母|中國未來航母%Future Chinese aircraft carrier",
"嚟自硫磺島的信|來自硫磺島的信%Letters from Iwo Jima",
"嚟賓市|來賓市%Laibin",
"北卡羅嚟納柏油腳跟男子籃球隊|北卡羅來納柏油腳跟男子籃球隊%North Carolina Tar Heels men's basketball",
"惠嚟縣|惠來縣%Huilai County",
"愛 未嚟式|愛 未來式%FutureSex/LoveSounds",
"懷嚟縣|懷來縣%Huailai County",
"未嚟日記|未來日記%Mirai Nikki",
"松嚟未祐|松來未祐%Miyu Matsuki",
"畢嚟德|畢來德%Jean François Billeter",
"緣嚟自有機|緣來自有機%The Green Grass of Home",
"緯嚟獵人籃球隊|緯來獵人籃球隊%Videoland Hunters",
"緯嚟電視網|緯來電視網%Videoland Television Network",
"興業銀行 （馬嚟西亞）|興業銀行 （馬來西亞）%RHB Bank",
"馬嚟亞大學|馬來亞大學%Asrama Ibnu Sina",
"馬嚟族|馬來族%Melayu Kingdom",
"馬嚟西亞聯邦大道系統|馬來西亞聯邦大道系統%Malaysian Federal Roads System",
"馬嚟西亞華語|馬來西亞華語%Malaysian Mandarin",
"馬嚟西亞高速大道系統|馬來西亞高速大道系統%Malaysian Expressway System",
"馬嚟語維基百科|馬來語維基百科%Malay Wikipedia",
"鬼嚟電|鬼來電%one missed call",
"在|喺",
"不喺乎|不在乎%bu4 zai4 hu1%/not mind/not care/",
"不喺話下|不在話下%bu4 zai4 hua4 xia4%/be nothing difficult/be a cinch/",
"不喺了|不在了%bu4 zai4 le5%/be dead/",
"不喺意|不在意%bu4 zai4 yi4%/pay no attention to/take no notice of/not mind/negligent/careless/",
"困難喺於|困難在於%kun4 nan2 zai4 yu2%/the problem is.../",
"老驥伏櫪志喺千里|老驥伏櫪志在千里%lao3 ji4 fu2 li4 zhi4 zai4 qian1 li3%/(lit.) an old steed in the stable still aspires to gallop 1000 li/(fig.) old people may still cherish high aspirations/",
"流亡喺海外|流亡在海外%liu2 wang2 zai4 hai3 wai4%/to be in exile overseas/",
"內喺的|內在的%nei4 zai4 de5%/inner/internal/",
"潛喺威脅|潛在威脅%qian2 zai4 wei1 xie2%/potential threat/potential menace/",
"勢喺必行|勢在必行%shi4 zai4 bi4 xing2%/be imperative/be required by circumstances/",
"所喺地|所在地%suo3 zai4 di4%/location/site/",
"喺車|在車%zai4 che1%/aboard/",
"喺傳輸過程中|在傳輸過程中%zai4 chuan2 shu1 guo4 cheng2 zhong1%/while transmitting/during transmission/",
"喺此處|在此處%zai4 ci3 chu4%/herein/",
"喺大多數情況下|在大多數情況下%zai4 da4 duo1 shu4 qing2 kuang4 xia4%/in most instances/",
"喺地下|在地下%zai4 di4 xia4%/underground/",
"喺附近|在附近%zai4 fu4 jin4%/nearby/",
"喺高處|在高處%zai4 gao1 chu4%/aloft/",
"喺很多方面|在很多方面%zai4 hen3 duo1 fang1 mian4%/in many aspects/in many regards/",
"喺後|在後%zai4 hou4%/behind/",
"喺戶外|在戶外%zai4 hu4 wai4%/outdoors/",
"喺今年年底|在今年年底%zai4 jin1 nian2 nian2 di3%/at the end of this year/",
"喺密切注意|在密切注意%zai4 mi4 qie4 zhu4 yi4%/to pay close attention (to sth)/",
"喺某種程度上|在某種程度上%zai4 mou3 zhong3 cheng2 du4 shang4%/to a certain extent/",
"喺內|在內%zai4 nei4%/including/",
"喺旁|在旁%zai4 pang2%/by (a place)/",
"喺﹍旁邊|在﹍旁邊%zai4 pang2 bian1%/alongside/",
"喺旁邊|在旁邊%zai4 pang2 bian1%/aside/",
"喺前|在前%zai4 qian2%/forward/",
"喺﹍期間|在﹍期間%zai4 qi2 jian1%/during/",
"喺其中|在其中%zai4 qi2 zhong1%/therein/wherein/",
"喺深處|在深處%zai4 shen1 chu4%/deeply/",
"喺室內|在室內%zai4 shi4 nei4%/indoors/",
"喺水步行|在水步行%zai4 shui3 bu4 xing2%/wade/",
"喺頭版|在頭版%zai4 tou2 ban3%/on the front page/",
"喺外|在外%zai4 wai4%/outer/",
"喺未來|在未來%zai4 wei4 lai2%/in the future/",
"喺下|在下%zai4 xia4%/under/",
"喺下方|在下方%zai4 xia4 fang1%/beneath/",
"喺下面|在下面%zai4 xia4 mian4%/underneath/",
"喺眼前|在眼前%zai4 yan3 qian2%/now/at the present/",
"喺野|在野%zai4 ye3%/be out of (political) office/out of power/",
"喺於|在於%zai4 yu2%/(the problem or explanation or advantage etc.) lies in (the fact that...)/to lie in/to reside in/to rest in/to depend on/",
"喺這期間|在這期間%zai4 zhe4 qi1 jian1%/during time/in this time/",
"喺﹍之間|在﹍之間%zai4 zhi1 jian1%/between/",
"喺﹍之內|在﹍之內%zai4 zhi1 nei4%/in/within/",
"喺﹍之旁|在﹍之旁%zai4 zhi1 pang2%/beside/",
"喺﹍之上|在﹍之上%zai4 zhi1 shang4%/above/upon/",
"喺之上|在之上%zai4 zhi1 shang4%/over/",
"喺﹍之下|在﹍之下%zai4 zhi1 xia4%/below/",
"喺﹍之中|在﹍之中%zai4 zhi1 zhong1%/amid/among/",
"正喺中國訪問|正在中國訪問%zheng4 zai4 zhong1 guo2 fang3 wen4%/during a trip to China/",
"一個美國人喺巴黎|一個美國人在巴黎%An American in Paris",
"不喺地主所有權|不在地主所有權%landed property",
"伊底帕斯喺柯隆納斯|伊底帕斯在柯隆納斯%Oedipus at Colonus",
"刀刺喺背傳說|刀刺在背傳說%stab-in-the-back legend",
"喺世界中心呼喊愛|在世界中心呼喊愛%Socrates in Love",
"喺天堂遇見的五個人|在天堂遇見的五個人%The Five People You Meet in Heaven",
"喺家自學|在家自學%homeschooling",
"喺殼和離殼|在殼和離殼%On shell and off shell",
"喺線|在線%On-line and off-line",
"喺線仿真器|在線仿真器%in-circuit emulator",
"喺路上|在路上%on the road",
"喺野黨|在野黨%Opposition",
"喺陶裡斯的伊菲格尼亞|在陶裡斯的伊菲格尼亞%Iphigenie auf Tauris",
"天使喺美國|天使在美國%Angels in America",
"好奇喬治喺唱歌|好奇喬治在唱歌%Sing-A-Longs and Lullabies for the Film Curious George",
"存喺主義|存在主義%existentialism",
"存喺主義神學|存在主義神學%Christian existentialism",
"存喺圖|存在圖%existential graph",
"存喺多個國家的島嶼列表|存在多個國家的島嶼列表%List of divided islands",
"存喺艦隊|存在艦隊%fleet in being",
"存喺量化|存在量化%existential quantification",
"安喺旭|安在旭%Ahn Jae Wook",
"已不存喺國家列表|已不存在國家列表%List of extinct states",
"愛喺聖誕節|愛在聖誕節%Last Christmas",
"憶喺步言中|憶在步言中%Memorial Address",
"歐洲國家喺印度的殖民地|歐洲國家在印度的殖民地%Colonial India",
"正喺編輯全球核子反應爐列表|正在編輯全球核子反應爐列表%list of nuclear reactors",
"猶太人喺中國|猶太人在中國%History of the Jews in China",
"現喺式|現在式%present tense",
"神奇動物喺哪裡|神奇動物在哪裡%Fantastic Beasts and Where to Find Them",
"禁止喺海底和洋底及其下面設置核武器和其他大規模毀滅性武器條約|禁止在海底和洋底及其下面設置核武器和其他大規模毀滅性武器條約%Seabed Arms Control Treaty",
"美國喺線|美國在線%AOL",
"美國喺臺協會|美國在臺協會%American Institute in Taiwan",
"美軍士兵喺硫磺島豎起國旗|美軍士兵在硫磺島豎起國旗%Raising the Flag on Iwo Jima",
"自由的喺線計算機詞典|自由的在線計算機詞典%Free On-line Dictionary of Computing",
"軸心國喺澳大利亞水域的軍事活動|軸心國在澳大利亞水域的軍事活動%Axis naval activity in Australian waters",
"遍喺遠洋桿菌|遍在遠洋桿菌%Pelagibacter ubique",
"金喺權|金在權%Jaegwon Kim",
"頭十位喺位最短的中國皇帝列表|頭十位在位最短的中國皇帝列表%List of shortest reigning Monarchs in China",
"頭十位喺位最長的中國皇帝列表|頭十位在位最長的中國皇帝列表%List of longest reigning Emperors in China",
"頭十位喺位最長的教宗列表|頭十位在位最長的教宗列表%List of popes by length of reign",
"不喺場證明|不在場證明%alibi",
"列寧喺1918|列寧在1918%Lenin in 1918",
"古惑仔之人喺江湖|古惑仔之人在江湖%Young and Dangerous 1",
"喺位時間最長的君主列表|在位時間最長的君主列表%List of longest reigning monarchs of all time",
"喺日朝鮮語|在日朝鮮語%Zainichi Korean language",
"喺熙|在熙%Jae Hee",
"已不存喺的NBA球隊列表|已不存在的NBA球隊列表%List of defunct National Basketball Association teams",
"愛喺哈彿|愛在哈彿%Love Story in Harvard",
"新教喺華傳教士列表|新教在華傳教士列表%List of Protestant missionaries in China",
"林喺山|林在山%Lam Joi-Shan",
"龍喺江湖|龍在江湖%Legacy of Rage",
"找|搵",
"搵錢|找錢%zhao3 qian2%/to give change/",
"尋搵滿月|尋找滿月%Full Moon o Sagashite",
"查搵表|查找表%lookup table",
"騙|呃",
"呃局|騙局%pian4 ju2%/fraud/swindle/",
"呃取|騙取%pian4 qu3%/to gain by cheating/",
"呃術|騙術%pian4 shu4%/trick/deceit/",
"呃子|騙子%pian4 zi5%/swindler/cheater/",
"尼日利亞呃徒|尼日利亞騙徒%e-mail fraud",
"呃局|騙局%hoax",
"龐茲呃局|龐茲騙局%Ponzi scheme",
"呃子菲利克斯·克魯爾的自白|騙子菲利克斯·克魯爾的自白%Confessions of Felix Krull",
"給|俾",
"俾與資格|給與資格%gei3 yu3 zi1 ge2%/qualify/",
"俾予|給予%ji3 yu3%/accord/give/show (respect)/",
"派俾工作|派給工作%pai4 gei3 gong1 zuo4%/to task/",
"殺雞俾猴看|殺雞給猴看%sha1 ji1 gei3 hou2 kan4%/'kill a chicken in front of a monkey' -- make an example out of someone (by punishing them) to frighten others/",
"供俾和需求|供給和需求%supply and demand",
"供俾的價格彈性|供給的價格彈性%price elasticity of supply",
"桑俾巴爾|桑給巴爾%Zanzibar",
"獻俾阿爾吉儂的花束|獻給阿爾吉儂的花束%Flowers for Algernon",
"米俾爾·阿庫別瑞|米給爾·阿庫別瑞%Miguel Alcubierre",
"俾藥途徑|給藥途徑%route of administration",
"俾一個未出生孩子的信|給一個未出生孩子的信%Letter to a Child Never Born",
"呢係|呢個係",
"嗰係|嗰個係",
"有冇有|有冇",
"為什麼|點解",
"冇什麼|冇咩%mei2 you3 shen2 me5%/there's nothing (... about it)/",
"養同埋|養和",
"飽同埋|飽和",
"求同埋|求和",
"親同埋|親和",
"緩同埋|緩和",
"總同埋|總和",
"義同埋|義和",
"調同埋|調和",
"和調同|和定",
"和調同|和諧",
"特立尼達同埋多巴哥共和國|特立尼達和多巴哥共和國%Economy of Trinidad and Tobago",
"波斯尼亞同埋黑塞哥維那社會主義共和國|波斯尼亞和黑塞哥維那社會主義共和國%Socialist Republic of Bosnia and Herzegovina",
"呢類|呢種%zhe4 lei4%/this kind (of)/",
"呢裡|呢度%zhe4 li3%/here/",
"呢麼|咁%zhe4 me5%/so (much)/like this/",
"呢天|今日%zhe4 tian1%/today/this day/",
"呢些|呢啲%zhe4 xie5%/these/",
"我們呢一家|我哋呢一家%Atashin'chi",
"我的呢一班|我嘅呢一班%Head of the Class",
"瞧！呢個人|瞧！呢個人%Ecce Homo",
"呢是我的國家|呢度係我嘅國家%This Is My Country",
"呢醜陋又美麗的世界|呢醜陋又美麗嘅世界%This Ugly Yet Beautiful World",
"某啲|某些%mou3 xie1%/some/certain (things)/",
"那啲|嗰啲%na4 xie1%/those/",
"這啲|呢啲%zhe4 xie5%/these/",
"到嗰裡|到嗰處%dao4 na4 li3%/thither/",
"嗰裡|嗰處%na4 li5%/there/that place/",
"嗰些|嗰啲%na4 xie1%/those/",
"嗰樣的|嗰樣嘅%na4 yang4 de5%/that kind of/that sort of/",
"不點麼|冇咩%bu4 zen3 me5%/not very/not particularly/",
"不點麼樣|冇咩樣%bu4 zen3 me5 yang4%/not up to much/very indifferent/",
"點麼|點%zen3 me5%/(interrogative pronoun)/how (can it be that)/",
"點麼樣|點樣%zen3 me5 yang4%/how about/(used in the negative)(not) so good/",
"點樣|點樣%zen3 yang4%/how/why/",
"察睇|察看%cha2 kan4%/to watch/to look carefully at/",
"觀睇|觀看%guan1 kan4%/to watch/to view/",
"睇不見|睇唔見%kan4 bu2 jian4%/unseen/",
"睇守者|看守者%kan4 shou3 zhe3%/watchman/",
"另眼相睇|另眼相看%ling4 yan3 xiang1 kan4%/to view in a new light/",
"殺雞給猴睇|殺雞給猴看%sha1 ji1 gei3 hou2 kan4%/'kill a chicken in front of a monkey' -- make an example out of someone (by punishing them) to frighten others/",
"細睇|細看%xi4 kan4%/peer/scan/",
"眼睇|眼看%yan3 kan4%/soon/in a moment/",
"從來冇有|從來冇%cong2 lai2 mei2 you3%/have",
"幾乎冇有|幾乎冇%ji1 hu1 mei2 you3%/scarcely/hardly any/",
"冇有|冇%mei2 you3%/haven't/hasn't/doesn't exist/to not have/to not be/",
"冇有必要|冇必要%mei2 you3 bi4 yao4%/there is no need to (do sth)/",
"冇有差別|冇差別%mei2 you3 cha1 bie2%/there is no difference/it makes no difference/",
"冇有聯繫|冇聯係%mei2 you3 lian2 xi4%/to be unrelated/",
"冇有人|冇人%mei2 you3 ren2%/nobody/",
"冇有生育能力|冇生育能力%mei2 you3 sheng1 yu4 neng2 li4%/infertile/unable to have children/",
"冇有什麼|冇乜%mei2 you3 shen2 me5%/there's nothing (... about it)/",
"冇有形狀|冇形狀%mei2 you3 xing2 zhuang4%/shapeless/",
"冇有知覺|冇知覺%mei2 you3 zhi1 jue2%/insensible/",
"四不一冇有|四不一冇%Four Noes and One Without",
"冇有銀彈|冇銀彈%No Silver Bullet",
"四要一冇有|四要一冇%Four Wants and One Without",
"冇有共產黨就冇有新中國|冇有共產黨就冇新中國%Without the Communist Party, There Would Be No New China",
"吉佢|吉他",
"其佢|其他",
"任何其佢|任何其他",
"佢們|佢哋%ta1 men5%/they/",
"佢們都|佢哋都%ta1 men5 dou1%/all of them/",
"佢們自己|佢哋自己%ta1 men2 zi4 ji3%/themselves/",
"佢與她的事情|佢與姖嘅事情%Kare Kano",
"其佢|其他",
"佢們|佢哋",
"目嘅|目的",
"嘅士|的士%taxi",
"我們|我哋%//",
"他們|佢哋%//",
"她們|姖哋%//",
"它們|佢哋%//",
"怹們|佢哋%//",
"牠們|佢哋%//",
"你們|你哋%//",
"人們|人哋%//",
"皆係|皆是",
"凡係|凡是",
"光係|光是",
"還係|還是",
"可係|可是",
"老係|老是",
"一係|一是",
"乃係|乃是",
"若係|若是",
"麼係|麼是",
"係否|是否",
"題係|題是",
"要係|要是",
"於係|於是",
"只係|只是",
"總係|總是",
"如係|如是",
"罷咗|罷了",
"得咗|得了",
"不咗|不了",
"咗之|了之",
"在咗|在了",
"極咗|極了",
"咗解|了解",
"本嚟|本來",
"從嚟|從來",
"後嚟|後來",
"古嚟|古來",
"回嚟|回來",
"將嚟|將來",
"近嚟|近來",
"嚟訪|來訪",
"嚟福槍|來福槍",
"嚟回嚟去地|來回來去地",
"嚟歷|來歷",
"嚟臨|來臨",
"嚟年|來年",
"嚟往|來往",
"嚟源|來源",
"嚟自|來自",
"歷嚟|歷來",
"馬嚟|馬來",
"年嚟|年來",
"外嚟|外來",
"往嚟|往來",
"未嚟|未來",
"下嚟|下來",
"希伯嚟|希伯來",
"以嚟|以來",
"由嚟|由來",
"原嚟|原來",
"周恩嚟|周恩來",
"尋搵|尋找%xun2 zhao3%/to seek/to look for/",
"查搵|查找%//",
"俾與|給與",
"供俾|供給",
"有冇有|有冇",
"|");
alert('1______'+awa2yuet[2]);
